// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_gsk_req.proto

#ifndef PROTOBUF_pb_5fgsk_5freq_2eproto__INCLUDED
#define PROTOBUF_pb_5fgsk_5freq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pb_5fgsk_5freq_2eproto();
void protobuf_AssignDesc_pb_5fgsk_5freq_2eproto();
void protobuf_ShutdownFile_pb_5fgsk_5freq_2eproto();

class pb_req_t_req;

// ===================================================================

class pb_req_t_req : public ::google::protobuf::Message {
 public:
  pb_req_t_req();
  virtual ~pb_req_t_req();

  pb_req_t_req(const pb_req_t_req& from);

  inline pb_req_t_req& operator=(const pb_req_t_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const pb_req_t_req& default_instance();

  void Swap(pb_req_t_req* other);

  // implements Message ----------------------------------------------

  pb_req_t_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pb_req_t_req& from);
  void MergeFrom(const pb_req_t_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 f_cmd = 1;
  inline bool has_f_cmd() const;
  inline void clear_f_cmd();
  static const int kFCmdFieldNumber = 1;
  inline ::google::protobuf::int32 f_cmd() const;
  inline void set_f_cmd(::google::protobuf::int32 value);

  // repeated int32 f_i_args = 2;
  inline int f_i_args_size() const;
  inline void clear_f_i_args();
  static const int kFIArgsFieldNumber = 2;
  inline ::google::protobuf::int32 f_i_args(int index) const;
  inline void set_f_i_args(int index, ::google::protobuf::int32 value);
  inline void add_f_i_args(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      f_i_args() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_f_i_args();

  // repeated string f_s_args = 3;
  inline int f_s_args_size() const;
  inline void clear_f_s_args();
  static const int kFSArgsFieldNumber = 3;
  inline const ::std::string& f_s_args(int index) const;
  inline ::std::string* mutable_f_s_args(int index);
  inline void set_f_s_args(int index, const ::std::string& value);
  inline void set_f_s_args(int index, const char* value);
  inline void set_f_s_args(int index, const char* value, size_t size);
  inline ::std::string* add_f_s_args();
  inline void add_f_s_args(const ::std::string& value);
  inline void add_f_s_args(const char* value);
  inline void add_f_s_args(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& f_s_args() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_f_s_args();

  // @@protoc_insertion_point(class_scope:pb_req_t_req)
 private:
  inline void set_has_f_cmd();
  inline void clear_has_f_cmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > f_i_args_;
  ::google::protobuf::RepeatedPtrField< ::std::string> f_s_args_;
  ::google::protobuf::int32 f_cmd_;
  friend void  protobuf_AddDesc_pb_5fgsk_5freq_2eproto();
  friend void protobuf_AssignDesc_pb_5fgsk_5freq_2eproto();
  friend void protobuf_ShutdownFile_pb_5fgsk_5freq_2eproto();

  void InitAsDefaultInstance();
  static pb_req_t_req* default_instance_;
};
// ===================================================================


// ===================================================================

// pb_req_t_req

// optional int32 f_cmd = 1;
inline bool pb_req_t_req::has_f_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void pb_req_t_req::set_has_f_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void pb_req_t_req::clear_has_f_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void pb_req_t_req::clear_f_cmd() {
  f_cmd_ = 0;
  clear_has_f_cmd();
}
inline ::google::protobuf::int32 pb_req_t_req::f_cmd() const {
  // @@protoc_insertion_point(field_get:pb_req_t_req.f_cmd)
  return f_cmd_;
}
inline void pb_req_t_req::set_f_cmd(::google::protobuf::int32 value) {
  set_has_f_cmd();
  f_cmd_ = value;
  // @@protoc_insertion_point(field_set:pb_req_t_req.f_cmd)
}

// repeated int32 f_i_args = 2;
inline int pb_req_t_req::f_i_args_size() const {
  return f_i_args_.size();
}
inline void pb_req_t_req::clear_f_i_args() {
  f_i_args_.Clear();
}
inline ::google::protobuf::int32 pb_req_t_req::f_i_args(int index) const {
  // @@protoc_insertion_point(field_get:pb_req_t_req.f_i_args)
  return f_i_args_.Get(index);
}
inline void pb_req_t_req::set_f_i_args(int index, ::google::protobuf::int32 value) {
  f_i_args_.Set(index, value);
  // @@protoc_insertion_point(field_set:pb_req_t_req.f_i_args)
}
inline void pb_req_t_req::add_f_i_args(::google::protobuf::int32 value) {
  f_i_args_.Add(value);
  // @@protoc_insertion_point(field_add:pb_req_t_req.f_i_args)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
pb_req_t_req::f_i_args() const {
  // @@protoc_insertion_point(field_list:pb_req_t_req.f_i_args)
  return f_i_args_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
pb_req_t_req::mutable_f_i_args() {
  // @@protoc_insertion_point(field_mutable_list:pb_req_t_req.f_i_args)
  return &f_i_args_;
}

// repeated string f_s_args = 3;
inline int pb_req_t_req::f_s_args_size() const {
  return f_s_args_.size();
}
inline void pb_req_t_req::clear_f_s_args() {
  f_s_args_.Clear();
}
inline const ::std::string& pb_req_t_req::f_s_args(int index) const {
  // @@protoc_insertion_point(field_get:pb_req_t_req.f_s_args)
  return f_s_args_.Get(index);
}
inline ::std::string* pb_req_t_req::mutable_f_s_args(int index) {
  // @@protoc_insertion_point(field_mutable:pb_req_t_req.f_s_args)
  return f_s_args_.Mutable(index);
}
inline void pb_req_t_req::set_f_s_args(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:pb_req_t_req.f_s_args)
  f_s_args_.Mutable(index)->assign(value);
}
inline void pb_req_t_req::set_f_s_args(int index, const char* value) {
  f_s_args_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:pb_req_t_req.f_s_args)
}
inline void pb_req_t_req::set_f_s_args(int index, const char* value, size_t size) {
  f_s_args_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pb_req_t_req.f_s_args)
}
inline ::std::string* pb_req_t_req::add_f_s_args() {
  return f_s_args_.Add();
}
inline void pb_req_t_req::add_f_s_args(const ::std::string& value) {
  f_s_args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:pb_req_t_req.f_s_args)
}
inline void pb_req_t_req::add_f_s_args(const char* value) {
  f_s_args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:pb_req_t_req.f_s_args)
}
inline void pb_req_t_req::add_f_s_args(const char* value, size_t size) {
  f_s_args_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:pb_req_t_req.f_s_args)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
pb_req_t_req::f_s_args() const {
  // @@protoc_insertion_point(field_list:pb_req_t_req.f_s_args)
  return f_s_args_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
pb_req_t_req::mutable_f_s_args() {
  // @@protoc_insertion_point(field_mutable_list:pb_req_t_req.f_s_args)
  return &f_s_args_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pb_5fgsk_5freq_2eproto__INCLUDED
