// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_gsk.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pb_gsk.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* pb_clt_t_user_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pb_clt_t_user_reflection_ = NULL;
const ::google::protobuf::Descriptor* pb_user_t_info_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pb_user_t_info_reflection_ = NULL;
const ::google::protobuf::Descriptor* pb_user_t_user_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pb_user_t_user_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pb_5fgsk_2eproto() {
  protobuf_AddDesc_pb_5fgsk_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pb_gsk.proto");
  GOOGLE_CHECK(file != NULL);
  pb_clt_t_user_descriptor_ = file->message_type(0);
  static const int pb_clt_t_user_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_clt_t_user, f_info_),
  };
  pb_clt_t_user_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      pb_clt_t_user_descriptor_,
      pb_clt_t_user::default_instance_,
      pb_clt_t_user_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_clt_t_user, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_clt_t_user, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(pb_clt_t_user));
  pb_user_t_info_descriptor_ = file->message_type(1);
  static const int pb_user_t_info_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_uin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_province_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_city_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_phone_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_company_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_years_of_working_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_job_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_job_title_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_auto_inc_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, f_last_req_time_),
  };
  pb_user_t_info_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      pb_user_t_info_descriptor_,
      pb_user_t_info::default_instance_,
      pb_user_t_info_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_info, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(pb_user_t_info));
  pb_user_t_user_descriptor_ = file->message_type(2);
  static const int pb_user_t_user_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_user, f_info_),
  };
  pb_user_t_user_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      pb_user_t_user_descriptor_,
      pb_user_t_user::default_instance_,
      pb_user_t_user_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_user, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_user_t_user, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(pb_user_t_user));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pb_5fgsk_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    pb_clt_t_user_descriptor_, &pb_clt_t_user::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    pb_user_t_info_descriptor_, &pb_user_t_info::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    pb_user_t_user_descriptor_, &pb_user_t_user::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pb_5fgsk_2eproto() {
  delete pb_clt_t_user::default_instance_;
  delete pb_clt_t_user_reflection_;
  delete pb_user_t_info::default_instance_;
  delete pb_user_t_info_reflection_;
  delete pb_user_t_user::default_instance_;
  delete pb_user_t_user_reflection_;
}

void protobuf_AddDesc_pb_5fgsk_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014pb_gsk.proto\"0\n\rpb_clt_t_user\022\037\n\006f_inf"
    "o\030\001 \001(\0132\017.pb_user_t_info\"\361\001\n\016pb_user_t_i"
    "nfo\022\r\n\005f_uin\030\001 \001(\r\022\022\n\nf_province\030\002 \001(\t\022\016"
    "\n\006f_city\030\003 \001(\t\022\017\n\007f_phone\030\004 \001(\t\022\016\n\006f_nam"
    "e\030\005 \001(\t\022\026\n\016f_company_type\030\006 \001(\t\022\032\n\022f_yea"
    "rs_of_working\030\007 \001(\t\022\022\n\nf_job_type\030\010 \001(\t\022"
    "\023\n\013f_job_title\030\t \001(\t\022\025\n\rf_auto_inc_id\030\n "
    "\001(\005\022\027\n\017f_last_req_time\030\013 \001(\005\"1\n\016pb_user_"
    "t_user\022\037\n\006f_info\030\001 \001(\0132\017.pb_user_t_info", 359);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pb_gsk.proto", &protobuf_RegisterTypes);
  pb_clt_t_user::default_instance_ = new pb_clt_t_user();
  pb_user_t_info::default_instance_ = new pb_user_t_info();
  pb_user_t_user::default_instance_ = new pb_user_t_user();
  pb_clt_t_user::default_instance_->InitAsDefaultInstance();
  pb_user_t_info::default_instance_->InitAsDefaultInstance();
  pb_user_t_user::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pb_5fgsk_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pb_5fgsk_2eproto {
  StaticDescriptorInitializer_pb_5fgsk_2eproto() {
    protobuf_AddDesc_pb_5fgsk_2eproto();
  }
} static_descriptor_initializer_pb_5fgsk_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int pb_clt_t_user::kFInfoFieldNumber;
#endif  // !_MSC_VER

pb_clt_t_user::pb_clt_t_user()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb_clt_t_user)
}

void pb_clt_t_user::InitAsDefaultInstance() {
  f_info_ = const_cast< ::pb_user_t_info*>(&::pb_user_t_info::default_instance());
}

pb_clt_t_user::pb_clt_t_user(const pb_clt_t_user& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb_clt_t_user)
}

void pb_clt_t_user::SharedCtor() {
  _cached_size_ = 0;
  f_info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

pb_clt_t_user::~pb_clt_t_user() {
  // @@protoc_insertion_point(destructor:pb_clt_t_user)
  SharedDtor();
}

void pb_clt_t_user::SharedDtor() {
  if (this != default_instance_) {
    delete f_info_;
  }
}

void pb_clt_t_user::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pb_clt_t_user::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pb_clt_t_user_descriptor_;
}

const pb_clt_t_user& pb_clt_t_user::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pb_5fgsk_2eproto();
  return *default_instance_;
}

pb_clt_t_user* pb_clt_t_user::default_instance_ = NULL;

pb_clt_t_user* pb_clt_t_user::New() const {
  return new pb_clt_t_user;
}

void pb_clt_t_user::Clear() {
  if (has_f_info()) {
    if (f_info_ != NULL) f_info_->::pb_user_t_info::Clear();
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool pb_clt_t_user::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb_clt_t_user)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .pb_user_t_info f_info = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_f_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb_clt_t_user)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb_clt_t_user)
  return false;
#undef DO_
}

void pb_clt_t_user::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb_clt_t_user)
  // optional .pb_user_t_info f_info = 1;
  if (has_f_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->f_info(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb_clt_t_user)
}

::google::protobuf::uint8* pb_clt_t_user::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_clt_t_user)
  // optional .pb_user_t_info f_info = 1;
  if (has_f_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->f_info(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb_clt_t_user)
  return target;
}

int pb_clt_t_user::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .pb_user_t_info f_info = 1;
    if (has_f_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->f_info());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pb_clt_t_user::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const pb_clt_t_user* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const pb_clt_t_user*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void pb_clt_t_user::MergeFrom(const pb_clt_t_user& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_f_info()) {
      mutable_f_info()->::pb_user_t_info::MergeFrom(from.f_info());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void pb_clt_t_user::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pb_clt_t_user::CopyFrom(const pb_clt_t_user& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pb_clt_t_user::IsInitialized() const {

  return true;
}

void pb_clt_t_user::Swap(pb_clt_t_user* other) {
  if (other != this) {
    std::swap(f_info_, other->f_info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata pb_clt_t_user::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pb_clt_t_user_descriptor_;
  metadata.reflection = pb_clt_t_user_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int pb_user_t_info::kFUinFieldNumber;
const int pb_user_t_info::kFProvinceFieldNumber;
const int pb_user_t_info::kFCityFieldNumber;
const int pb_user_t_info::kFPhoneFieldNumber;
const int pb_user_t_info::kFNameFieldNumber;
const int pb_user_t_info::kFCompanyTypeFieldNumber;
const int pb_user_t_info::kFYearsOfWorkingFieldNumber;
const int pb_user_t_info::kFJobTypeFieldNumber;
const int pb_user_t_info::kFJobTitleFieldNumber;
const int pb_user_t_info::kFAutoIncIdFieldNumber;
const int pb_user_t_info::kFLastReqTimeFieldNumber;
#endif  // !_MSC_VER

pb_user_t_info::pb_user_t_info()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb_user_t_info)
}

void pb_user_t_info::InitAsDefaultInstance() {
}

pb_user_t_info::pb_user_t_info(const pb_user_t_info& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb_user_t_info)
}

void pb_user_t_info::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  f_uin_ = 0u;
  f_province_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_city_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_phone_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_company_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_years_of_working_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_job_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_job_title_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  f_auto_inc_id_ = 0;
  f_last_req_time_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

pb_user_t_info::~pb_user_t_info() {
  // @@protoc_insertion_point(destructor:pb_user_t_info)
  SharedDtor();
}

void pb_user_t_info::SharedDtor() {
  if (f_province_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_province_;
  }
  if (f_city_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_city_;
  }
  if (f_phone_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_phone_;
  }
  if (f_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_name_;
  }
  if (f_company_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_company_type_;
  }
  if (f_years_of_working_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_years_of_working_;
  }
  if (f_job_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_job_type_;
  }
  if (f_job_title_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete f_job_title_;
  }
  if (this != default_instance_) {
  }
}

void pb_user_t_info::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pb_user_t_info::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pb_user_t_info_descriptor_;
}

const pb_user_t_info& pb_user_t_info::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pb_5fgsk_2eproto();
  return *default_instance_;
}

pb_user_t_info* pb_user_t_info::default_instance_ = NULL;

pb_user_t_info* pb_user_t_info::New() const {
  return new pb_user_t_info;
}

void pb_user_t_info::Clear() {
  if (_has_bits_[0 / 32] & 255) {
    f_uin_ = 0u;
    if (has_f_province()) {
      if (f_province_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_province_->clear();
      }
    }
    if (has_f_city()) {
      if (f_city_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_city_->clear();
      }
    }
    if (has_f_phone()) {
      if (f_phone_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_phone_->clear();
      }
    }
    if (has_f_name()) {
      if (f_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_name_->clear();
      }
    }
    if (has_f_company_type()) {
      if (f_company_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_company_type_->clear();
      }
    }
    if (has_f_years_of_working()) {
      if (f_years_of_working_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_years_of_working_->clear();
      }
    }
    if (has_f_job_type()) {
      if (f_job_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_job_type_->clear();
      }
    }
  }
  if (_has_bits_[8 / 32] & 1792) {
    if (has_f_job_title()) {
      if (f_job_title_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        f_job_title_->clear();
      }
    }
    f_auto_inc_id_ = 0;
    f_last_req_time_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool pb_user_t_info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb_user_t_info)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 f_uin = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &f_uin_)));
          set_has_f_uin();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_f_province;
        break;
      }

      // optional string f_province = 2;
      case 2: {
        if (tag == 18) {
         parse_f_province:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_province()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_province().data(), this->f_province().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_province");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_f_city;
        break;
      }

      // optional string f_city = 3;
      case 3: {
        if (tag == 26) {
         parse_f_city:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_city()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_city().data(), this->f_city().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_city");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_f_phone;
        break;
      }

      // optional string f_phone = 4;
      case 4: {
        if (tag == 34) {
         parse_f_phone:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_phone()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_phone().data(), this->f_phone().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_phone");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_f_name;
        break;
      }

      // optional string f_name = 5;
      case 5: {
        if (tag == 42) {
         parse_f_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_name().data(), this->f_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_f_company_type;
        break;
      }

      // optional string f_company_type = 6;
      case 6: {
        if (tag == 50) {
         parse_f_company_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_company_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_company_type().data(), this->f_company_type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_company_type");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_f_years_of_working;
        break;
      }

      // optional string f_years_of_working = 7;
      case 7: {
        if (tag == 58) {
         parse_f_years_of_working:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_years_of_working()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_years_of_working().data(), this->f_years_of_working().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_years_of_working");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_f_job_type;
        break;
      }

      // optional string f_job_type = 8;
      case 8: {
        if (tag == 66) {
         parse_f_job_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_job_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_job_type().data(), this->f_job_type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_job_type");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_f_job_title;
        break;
      }

      // optional string f_job_title = 9;
      case 9: {
        if (tag == 74) {
         parse_f_job_title:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f_job_title()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_job_title().data(), this->f_job_title().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_job_title");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_f_auto_inc_id;
        break;
      }

      // optional int32 f_auto_inc_id = 10;
      case 10: {
        if (tag == 80) {
         parse_f_auto_inc_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &f_auto_inc_id_)));
          set_has_f_auto_inc_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_f_last_req_time;
        break;
      }

      // optional int32 f_last_req_time = 11;
      case 11: {
        if (tag == 88) {
         parse_f_last_req_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &f_last_req_time_)));
          set_has_f_last_req_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb_user_t_info)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb_user_t_info)
  return false;
#undef DO_
}

void pb_user_t_info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb_user_t_info)
  // optional uint32 f_uin = 1;
  if (has_f_uin()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->f_uin(), output);
  }

  // optional string f_province = 2;
  if (has_f_province()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_province().data(), this->f_province().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_province");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->f_province(), output);
  }

  // optional string f_city = 3;
  if (has_f_city()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_city().data(), this->f_city().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_city");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->f_city(), output);
  }

  // optional string f_phone = 4;
  if (has_f_phone()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_phone().data(), this->f_phone().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_phone");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->f_phone(), output);
  }

  // optional string f_name = 5;
  if (has_f_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_name().data(), this->f_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->f_name(), output);
  }

  // optional string f_company_type = 6;
  if (has_f_company_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_company_type().data(), this->f_company_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_company_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->f_company_type(), output);
  }

  // optional string f_years_of_working = 7;
  if (has_f_years_of_working()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_years_of_working().data(), this->f_years_of_working().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_years_of_working");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->f_years_of_working(), output);
  }

  // optional string f_job_type = 8;
  if (has_f_job_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_job_type().data(), this->f_job_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_job_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->f_job_type(), output);
  }

  // optional string f_job_title = 9;
  if (has_f_job_title()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_job_title().data(), this->f_job_title().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_job_title");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->f_job_title(), output);
  }

  // optional int32 f_auto_inc_id = 10;
  if (has_f_auto_inc_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->f_auto_inc_id(), output);
  }

  // optional int32 f_last_req_time = 11;
  if (has_f_last_req_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->f_last_req_time(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb_user_t_info)
}

::google::protobuf::uint8* pb_user_t_info::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_user_t_info)
  // optional uint32 f_uin = 1;
  if (has_f_uin()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->f_uin(), target);
  }

  // optional string f_province = 2;
  if (has_f_province()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_province().data(), this->f_province().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_province");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->f_province(), target);
  }

  // optional string f_city = 3;
  if (has_f_city()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_city().data(), this->f_city().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_city");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->f_city(), target);
  }

  // optional string f_phone = 4;
  if (has_f_phone()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_phone().data(), this->f_phone().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_phone");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->f_phone(), target);
  }

  // optional string f_name = 5;
  if (has_f_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_name().data(), this->f_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->f_name(), target);
  }

  // optional string f_company_type = 6;
  if (has_f_company_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_company_type().data(), this->f_company_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_company_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->f_company_type(), target);
  }

  // optional string f_years_of_working = 7;
  if (has_f_years_of_working()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_years_of_working().data(), this->f_years_of_working().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_years_of_working");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->f_years_of_working(), target);
  }

  // optional string f_job_type = 8;
  if (has_f_job_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_job_type().data(), this->f_job_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_job_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->f_job_type(), target);
  }

  // optional string f_job_title = 9;
  if (has_f_job_title()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_job_title().data(), this->f_job_title().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_job_title");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->f_job_title(), target);
  }

  // optional int32 f_auto_inc_id = 10;
  if (has_f_auto_inc_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->f_auto_inc_id(), target);
  }

  // optional int32 f_last_req_time = 11;
  if (has_f_last_req_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->f_last_req_time(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb_user_t_info)
  return target;
}

int pb_user_t_info::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 f_uin = 1;
    if (has_f_uin()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->f_uin());
    }

    // optional string f_province = 2;
    if (has_f_province()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_province());
    }

    // optional string f_city = 3;
    if (has_f_city()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_city());
    }

    // optional string f_phone = 4;
    if (has_f_phone()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_phone());
    }

    // optional string f_name = 5;
    if (has_f_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_name());
    }

    // optional string f_company_type = 6;
    if (has_f_company_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_company_type());
    }

    // optional string f_years_of_working = 7;
    if (has_f_years_of_working()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_years_of_working());
    }

    // optional string f_job_type = 8;
    if (has_f_job_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_job_type());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string f_job_title = 9;
    if (has_f_job_title()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f_job_title());
    }

    // optional int32 f_auto_inc_id = 10;
    if (has_f_auto_inc_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->f_auto_inc_id());
    }

    // optional int32 f_last_req_time = 11;
    if (has_f_last_req_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->f_last_req_time());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pb_user_t_info::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const pb_user_t_info* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const pb_user_t_info*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void pb_user_t_info::MergeFrom(const pb_user_t_info& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_f_uin()) {
      set_f_uin(from.f_uin());
    }
    if (from.has_f_province()) {
      set_f_province(from.f_province());
    }
    if (from.has_f_city()) {
      set_f_city(from.f_city());
    }
    if (from.has_f_phone()) {
      set_f_phone(from.f_phone());
    }
    if (from.has_f_name()) {
      set_f_name(from.f_name());
    }
    if (from.has_f_company_type()) {
      set_f_company_type(from.f_company_type());
    }
    if (from.has_f_years_of_working()) {
      set_f_years_of_working(from.f_years_of_working());
    }
    if (from.has_f_job_type()) {
      set_f_job_type(from.f_job_type());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_f_job_title()) {
      set_f_job_title(from.f_job_title());
    }
    if (from.has_f_auto_inc_id()) {
      set_f_auto_inc_id(from.f_auto_inc_id());
    }
    if (from.has_f_last_req_time()) {
      set_f_last_req_time(from.f_last_req_time());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void pb_user_t_info::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pb_user_t_info::CopyFrom(const pb_user_t_info& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pb_user_t_info::IsInitialized() const {

  return true;
}

void pb_user_t_info::Swap(pb_user_t_info* other) {
  if (other != this) {
    std::swap(f_uin_, other->f_uin_);
    std::swap(f_province_, other->f_province_);
    std::swap(f_city_, other->f_city_);
    std::swap(f_phone_, other->f_phone_);
    std::swap(f_name_, other->f_name_);
    std::swap(f_company_type_, other->f_company_type_);
    std::swap(f_years_of_working_, other->f_years_of_working_);
    std::swap(f_job_type_, other->f_job_type_);
    std::swap(f_job_title_, other->f_job_title_);
    std::swap(f_auto_inc_id_, other->f_auto_inc_id_);
    std::swap(f_last_req_time_, other->f_last_req_time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata pb_user_t_info::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pb_user_t_info_descriptor_;
  metadata.reflection = pb_user_t_info_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int pb_user_t_user::kFInfoFieldNumber;
#endif  // !_MSC_VER

pb_user_t_user::pb_user_t_user()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb_user_t_user)
}

void pb_user_t_user::InitAsDefaultInstance() {
  f_info_ = const_cast< ::pb_user_t_info*>(&::pb_user_t_info::default_instance());
}

pb_user_t_user::pb_user_t_user(const pb_user_t_user& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb_user_t_user)
}

void pb_user_t_user::SharedCtor() {
  _cached_size_ = 0;
  f_info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

pb_user_t_user::~pb_user_t_user() {
  // @@protoc_insertion_point(destructor:pb_user_t_user)
  SharedDtor();
}

void pb_user_t_user::SharedDtor() {
  if (this != default_instance_) {
    delete f_info_;
  }
}

void pb_user_t_user::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pb_user_t_user::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pb_user_t_user_descriptor_;
}

const pb_user_t_user& pb_user_t_user::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pb_5fgsk_2eproto();
  return *default_instance_;
}

pb_user_t_user* pb_user_t_user::default_instance_ = NULL;

pb_user_t_user* pb_user_t_user::New() const {
  return new pb_user_t_user;
}

void pb_user_t_user::Clear() {
  if (has_f_info()) {
    if (f_info_ != NULL) f_info_->::pb_user_t_info::Clear();
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool pb_user_t_user::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb_user_t_user)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .pb_user_t_info f_info = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_f_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb_user_t_user)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb_user_t_user)
  return false;
#undef DO_
}

void pb_user_t_user::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb_user_t_user)
  // optional .pb_user_t_info f_info = 1;
  if (has_f_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->f_info(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb_user_t_user)
}

::google::protobuf::uint8* pb_user_t_user::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_user_t_user)
  // optional .pb_user_t_info f_info = 1;
  if (has_f_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->f_info(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb_user_t_user)
  return target;
}

int pb_user_t_user::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .pb_user_t_info f_info = 1;
    if (has_f_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->f_info());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pb_user_t_user::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const pb_user_t_user* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const pb_user_t_user*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void pb_user_t_user::MergeFrom(const pb_user_t_user& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_f_info()) {
      mutable_f_info()->::pb_user_t_info::MergeFrom(from.f_info());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void pb_user_t_user::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pb_user_t_user::CopyFrom(const pb_user_t_user& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pb_user_t_user::IsInitialized() const {

  return true;
}

void pb_user_t_user::Swap(pb_user_t_user* other) {
  if (other != this) {
    std::swap(f_info_, other->f_info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata pb_user_t_user::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pb_user_t_user_descriptor_;
  metadata.reflection = pb_user_t_user_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
