// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_gsk_req.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pb_gsk_req.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* pb_req_t_req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pb_req_t_req_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pb_5fgsk_5freq_2eproto() {
  protobuf_AddDesc_pb_5fgsk_5freq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pb_gsk_req.proto");
  GOOGLE_CHECK(file != NULL);
  pb_req_t_req_descriptor_ = file->message_type(0);
  static const int pb_req_t_req_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_req_t_req, f_cmd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_req_t_req, f_i_args_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_req_t_req, f_s_args_),
  };
  pb_req_t_req_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      pb_req_t_req_descriptor_,
      pb_req_t_req::default_instance_,
      pb_req_t_req_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_req_t_req, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_req_t_req, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(pb_req_t_req));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pb_5fgsk_5freq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    pb_req_t_req_descriptor_, &pb_req_t_req::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pb_5fgsk_5freq_2eproto() {
  delete pb_req_t_req::default_instance_;
  delete pb_req_t_req_reflection_;
}

void protobuf_AddDesc_pb_5fgsk_5freq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020pb_gsk_req.proto\"A\n\014pb_req_t_req\022\r\n\005f_"
    "cmd\030\001 \001(\005\022\020\n\010f_i_args\030\002 \003(\005\022\020\n\010f_s_args\030"
    "\003 \003(\t", 85);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pb_gsk_req.proto", &protobuf_RegisterTypes);
  pb_req_t_req::default_instance_ = new pb_req_t_req();
  pb_req_t_req::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pb_5fgsk_5freq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pb_5fgsk_5freq_2eproto {
  StaticDescriptorInitializer_pb_5fgsk_5freq_2eproto() {
    protobuf_AddDesc_pb_5fgsk_5freq_2eproto();
  }
} static_descriptor_initializer_pb_5fgsk_5freq_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int pb_req_t_req::kFCmdFieldNumber;
const int pb_req_t_req::kFIArgsFieldNumber;
const int pb_req_t_req::kFSArgsFieldNumber;
#endif  // !_MSC_VER

pb_req_t_req::pb_req_t_req()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb_req_t_req)
}

void pb_req_t_req::InitAsDefaultInstance() {
}

pb_req_t_req::pb_req_t_req(const pb_req_t_req& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb_req_t_req)
}

void pb_req_t_req::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  f_cmd_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

pb_req_t_req::~pb_req_t_req() {
  // @@protoc_insertion_point(destructor:pb_req_t_req)
  SharedDtor();
}

void pb_req_t_req::SharedDtor() {
  if (this != default_instance_) {
  }
}

void pb_req_t_req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pb_req_t_req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pb_req_t_req_descriptor_;
}

const pb_req_t_req& pb_req_t_req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pb_5fgsk_5freq_2eproto();
  return *default_instance_;
}

pb_req_t_req* pb_req_t_req::default_instance_ = NULL;

pb_req_t_req* pb_req_t_req::New() const {
  return new pb_req_t_req;
}

void pb_req_t_req::Clear() {
  f_cmd_ = 0;
  f_i_args_.Clear();
  f_s_args_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool pb_req_t_req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb_req_t_req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 f_cmd = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &f_cmd_)));
          set_has_f_cmd();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_f_i_args;
        break;
      }

      // repeated int32 f_i_args = 2;
      case 2: {
        if (tag == 16) {
         parse_f_i_args:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_f_i_args())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_f_i_args())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_f_i_args;
        if (input->ExpectTag(26)) goto parse_f_s_args;
        break;
      }

      // repeated string f_s_args = 3;
      case 3: {
        if (tag == 26) {
         parse_f_s_args:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_f_s_args()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->f_s_args(this->f_s_args_size() - 1).data(),
            this->f_s_args(this->f_s_args_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "f_s_args");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_f_s_args;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb_req_t_req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb_req_t_req)
  return false;
#undef DO_
}

void pb_req_t_req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb_req_t_req)
  // optional int32 f_cmd = 1;
  if (has_f_cmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->f_cmd(), output);
  }

  // repeated int32 f_i_args = 2;
  for (int i = 0; i < this->f_i_args_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->f_i_args(i), output);
  }

  // repeated string f_s_args = 3;
  for (int i = 0; i < this->f_s_args_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->f_s_args(i).data(), this->f_s_args(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "f_s_args");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->f_s_args(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb_req_t_req)
}

::google::protobuf::uint8* pb_req_t_req::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_req_t_req)
  // optional int32 f_cmd = 1;
  if (has_f_cmd()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->f_cmd(), target);
  }

  // repeated int32 f_i_args = 2;
  for (int i = 0; i < this->f_i_args_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->f_i_args(i), target);
  }

  // repeated string f_s_args = 3;
  for (int i = 0; i < this->f_s_args_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->f_s_args(i).data(), this->f_s_args(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "f_s_args");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->f_s_args(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb_req_t_req)
  return target;
}

int pb_req_t_req::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 f_cmd = 1;
    if (has_f_cmd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->f_cmd());
    }

  }
  // repeated int32 f_i_args = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->f_i_args_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->f_i_args(i));
    }
    total_size += 1 * this->f_i_args_size() + data_size;
  }

  // repeated string f_s_args = 3;
  total_size += 1 * this->f_s_args_size();
  for (int i = 0; i < this->f_s_args_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->f_s_args(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pb_req_t_req::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const pb_req_t_req* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const pb_req_t_req*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void pb_req_t_req::MergeFrom(const pb_req_t_req& from) {
  GOOGLE_CHECK_NE(&from, this);
  f_i_args_.MergeFrom(from.f_i_args_);
  f_s_args_.MergeFrom(from.f_s_args_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_f_cmd()) {
      set_f_cmd(from.f_cmd());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void pb_req_t_req::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pb_req_t_req::CopyFrom(const pb_req_t_req& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pb_req_t_req::IsInitialized() const {

  return true;
}

void pb_req_t_req::Swap(pb_req_t_req* other) {
  if (other != this) {
    std::swap(f_cmd_, other->f_cmd_);
    f_i_args_.Swap(&other->f_i_args_);
    f_s_args_.Swap(&other->f_s_args_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata pb_req_t_req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pb_req_t_req_descriptor_;
  metadata.reflection = pb_req_t_req_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
