/* ==========================================================
 * gsk project
 * 
 * ==========================================================
 * data_def.h
 * Author : yongshengzhao@vip.qq.com
 * Date 	: 2013-05-11 
 *
 * Generated by system . DO NOT EDIT!
 *
 * ========================================================== */

#ifndef __YS_CMD_INFO_H__
#define __YS_CMD_INFO_H__

#include <iostream>
#include <string.h>
#include <unordered_map>
#include "cmd_def.h"

using namespace std; 

void InitCmdInfo( unordered_map< int , string > &mapInfo )
{

		mapInfo.insert( pair< int , string >( CMD_REQ_INNER_CREATE_ACCOUNT, "创建帐户" ) );
		mapInfo.insert( pair< int , string >( CMD_REQ_INNER_LOGIN, "登陆" ) );
		mapInfo.insert( pair< int , string >( CMD_REQ_THRIDPARTY_LOGIN, "第三方登陆" ) );
		mapInfo.insert( pair< int , string >( CMD_REQ_CHANG_PASSWD, "修改密码" ) );
		mapInfo.insert( pair< int , string >( CMD_REQ_SERVER_LOGIN, "内部登陆" ) );
		mapInfo.insert( pair< int , string >( CMD_REQ_ACCOUNT_TO_UIN, "账号转UIN" ) );
		mapInfo.insert( pair< int , string >( CMD_USER_CREATE, "创建用户" ) );
		mapInfo.insert( pair< int , string >( CMD_USER_INFO, "获取用户数据" ) );
		mapInfo.insert( pair< int , string >( CMD_PUSH, "PUSH" ) );

}
#endif


/* ==========================================================
 *
 * Generated by system . DO NOT EDIT!
 * ========================================================== */


