/* ==========================================================
 * gsk project
 * 
 * ==========================================================
 * data_init.h
 * Author : yongshengzhao@vip.qq.com
 * Date         : 2013-05-11
 *
 * Generated by system . DO NOT EDIT!
 *
 * ========================================================== */

#ifndef __YS_DATA_INIT_H__
#define __YS_DATA_INIT_H__

#include "def.h"
#include "inc.h"
#include "data_def.h"
#include "Common.h"
#include "MyDB.h"
Mysql mysql;
//INIT_DATA
void InitConfigInfo(CData<ConfigInfo> *pstData)
{
    pstData->clear();
    Mysql::MysqlData data;
    ConfigInfo stItem ;

    //t_config
    data = mysql.queryRecord(" SELECT * FROM t_config; ");
    for(size_t i = 0; i < data.size(); i++)
    {
        //3个字段
        stItem.id = Common::strto<uint64_t>(data[i]["f_id"]) ;
        stItem.strValue = data[i]["f_value"];
        pstData->SetNode(stItem.id, stItem);
    }
}
void InitVersionInfo(CData<VersionInfo> *pstData)
{
    pstData->clear();
    Mysql::MysqlData data;
    VersionInfo stItem ;

    //t_version
    data = mysql.queryRecord(" SELECT * FROM t_version; ");
    for(size_t i = 0; i < data.size(); i++)
    {
        //3个字段
        stItem.id = Common::strto<uint64_t>(data[i]["f_id"]) ;
        stItem.strDesc = data[i]["f_desc"];
        pstData->SetNode(stItem.id, stItem);
    }
}

#endif

/* ==========================================================
 *
 * Generated by system . DO NOT EDIT!
 * ========================================================== */


