/*==========================================================
 * gsk project
 * 
 * ==========================================================
 * logic_init.h
 * Author : yongshengzhao@vip.qq.com
 * Date 	: 2013-05-11 
 *
 * Generated by system . DO NOT EDIT!
 *
 * ========================================================== */

#ifndef __YS_GSK_LOGIC_INIT_H__
#define __YS_GSK_LOGIC_INIT_H__

#include "gsk_logic_common.h"


CData<ConfigInfo> *g_pstConfigInfo = new CData<ConfigInfo>();
CData<VersionInfo> *g_pstVersionInfo = new CData<VersionInfo>();


void LoadDataInfo( )
{
    LOG_PRINT(".");
    InitConfigInfo( g_pstConfigInfo );
    LOG_PRINT("InitConfigInfo data size : %lu",g_pstConfigInfo->size());
    InitVersionInfo( g_pstVersionInfo );
    LOG_PRINT("InitVersionInfo data size : %lu",g_pstVersionInfo->size());
}


void LoadData()
{
    char szDBHost[16];
    int  iDBPort;
    char szDBUser[64];
    char szDBPswd[64];
    char szDBName[128];
    
    OI_Cfg_GetConfig("../conf/gsk.conf",
                     "DB_HOST", CFG_STRING, szDBHost, "192.168.1.107", sizeof(szDBHost),
                     "DB_PORT", CFG_INT, &(iDBPort), 3306,
                     "DB_USER", CFG_STRING, szDBUser, "root", sizeof(szDBUser),
                     "DB_PSWD", CFG_STRING, szDBPswd, "lavaclan", sizeof(szDBPswd),
                     "DB_NAME", CFG_STRING, szDBName, "gsk_srv", sizeof(szDBName),
                     NULL
                     );
    try{
        mysql.init(szDBHost,  szDBUser, szDBPswd, szDBName, "utf8" , iDBPort);
        mysql.connect();
    }
    catch(exception &ex)
    {
        cout << ex.what() << endl;
    }

    LoadDataInfo();

    g_pCltInfo = new CClientInfo();
    if( g_pCltInfo == NULL )
    {
        LOG_PRINT("CLTINFO INIT FAILED!");
    }
 
    g_pCfg = CConfig::Instance( g_pstConfigInfo );
    if( g_pCfg == NULL )
    {
        LOG_PRINT("CONFIG INIT FAILED!");
    }
    
}

#endif

/* ==========================================================
 *
 * Generated by system . DO NOT EDIT!
 * ========================================================== */


