// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_gsk_req.proto

package com.gsk.protobuf;


public final class PbGskReq {
  private PbGskReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface pb_req_t_reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb_req_t_req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 f_cmd = 1;</code>
     */
    boolean hasFCmd();
    /**
     * <code>optional int32 f_cmd = 1;</code>
     */
    int getFCmd();

    /**
     * <code>repeated int32 f_i_args = 2;</code>
     */
    java.util.List<java.lang.Integer> getFIArgsList();
    /**
     * <code>repeated int32 f_i_args = 2;</code>
     */
    int getFIArgsCount();
    /**
     * <code>repeated int32 f_i_args = 2;</code>
     */
    int getFIArgs(int index);

    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getFSArgsList();
    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    int getFSArgsCount();
    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    java.lang.String getFSArgs(int index);
    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    com.google.protobuf.ByteString
        getFSArgsBytes(int index);
  }
  /**
   * Protobuf type {@code pb_req_t_req}
   *
   * <pre>
   * gsk_pb_req_data;
   *----------------------------------------------------
   * </pre>
   */
  public static final class pb_req_t_req extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb_req_t_req)
      pb_req_t_reqOrBuilder {
    // Use pb_req_t_req.newBuilder() to construct.
    private pb_req_t_req(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private pb_req_t_req(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final pb_req_t_req defaultInstance;
    public static pb_req_t_req getDefaultInstance() {
      return defaultInstance;
    }

    public pb_req_t_req getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private pb_req_t_req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fCmd_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                fIArgs_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              fIArgs_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                fIArgs_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                fIArgs_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                fSArgs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              fSArgs_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          fIArgs_ = java.util.Collections.unmodifiableList(fIArgs_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          fSArgs_ = fSArgs_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PbGskReq.internal_static_pb_req_t_req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PbGskReq.internal_static_pb_req_t_req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PbGskReq.pb_req_t_req.class, PbGskReq.pb_req_t_req.Builder.class);
    }

    public static com.google.protobuf.Parser<pb_req_t_req> PARSER =
        new com.google.protobuf.AbstractParser<pb_req_t_req>() {
      public pb_req_t_req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new pb_req_t_req(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<pb_req_t_req> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int F_CMD_FIELD_NUMBER = 1;
    private int fCmd_;
    /**
     * <code>optional int32 f_cmd = 1;</code>
     */
    public boolean hasFCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 f_cmd = 1;</code>
     */
    public int getFCmd() {
      return fCmd_;
    }

    public static final int F_I_ARGS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> fIArgs_;
    /**
     * <code>repeated int32 f_i_args = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getFIArgsList() {
      return fIArgs_;
    }
    /**
     * <code>repeated int32 f_i_args = 2;</code>
     */
    public int getFIArgsCount() {
      return fIArgs_.size();
    }
    /**
     * <code>repeated int32 f_i_args = 2;</code>
     */
    public int getFIArgs(int index) {
      return fIArgs_.get(index);
    }

    public static final int F_S_ARGS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList fSArgs_;
    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFSArgsList() {
      return fSArgs_;
    }
    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    public int getFSArgsCount() {
      return fSArgs_.size();
    }
    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    public java.lang.String getFSArgs(int index) {
      return fSArgs_.get(index);
    }
    /**
     * <code>repeated string f_s_args = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFSArgsBytes(int index) {
      return fSArgs_.getByteString(index);
    }

    private void initFields() {
      fCmd_ = 0;
      fIArgs_ = java.util.Collections.emptyList();
      fSArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, fCmd_);
      }
      for (int i = 0; i < fIArgs_.size(); i++) {
        output.writeInt32(2, fIArgs_.get(i));
      }
      for (int i = 0; i < fSArgs_.size(); i++) {
        output.writeBytes(3, fSArgs_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fCmd_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fIArgs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(fIArgs_.get(i));
        }
        size += dataSize;
        size += 1 * getFIArgsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fSArgs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fSArgs_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFSArgsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PbGskReq.pb_req_t_req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PbGskReq.pb_req_t_req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PbGskReq.pb_req_t_req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PbGskReq.pb_req_t_req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PbGskReq.pb_req_t_req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PbGskReq.pb_req_t_req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PbGskReq.pb_req_t_req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PbGskReq.pb_req_t_req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PbGskReq.pb_req_t_req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PbGskReq.pb_req_t_req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PbGskReq.pb_req_t_req prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb_req_t_req}
     *
     * <pre>
     * gsk_pb_req_data;
     *----------------------------------------------------
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb_req_t_req)
        PbGskReq.pb_req_t_reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PbGskReq.internal_static_pb_req_t_req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PbGskReq.internal_static_pb_req_t_req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PbGskReq.pb_req_t_req.class, PbGskReq.pb_req_t_req.Builder.class);
      }

      // Construct using PbGskReq.pb_req_t_req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fCmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fIArgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        fSArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PbGskReq.internal_static_pb_req_t_req_descriptor;
      }

      public PbGskReq.pb_req_t_req getDefaultInstanceForType() {
        return PbGskReq.pb_req_t_req.getDefaultInstance();
      }

      public PbGskReq.pb_req_t_req build() {
        PbGskReq.pb_req_t_req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PbGskReq.pb_req_t_req buildPartial() {
        PbGskReq.pb_req_t_req result = new PbGskReq.pb_req_t_req(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fCmd_ = fCmd_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          fIArgs_ = java.util.Collections.unmodifiableList(fIArgs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fIArgs_ = fIArgs_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          fSArgs_ = fSArgs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.fSArgs_ = fSArgs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PbGskReq.pb_req_t_req) {
          return mergeFrom((PbGskReq.pb_req_t_req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PbGskReq.pb_req_t_req other) {
        if (other == PbGskReq.pb_req_t_req.getDefaultInstance()) return this;
        if (other.hasFCmd()) {
          setFCmd(other.getFCmd());
        }
        if (!other.fIArgs_.isEmpty()) {
          if (fIArgs_.isEmpty()) {
            fIArgs_ = other.fIArgs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFIArgsIsMutable();
            fIArgs_.addAll(other.fIArgs_);
          }
          onChanged();
        }
        if (!other.fSArgs_.isEmpty()) {
          if (fSArgs_.isEmpty()) {
            fSArgs_ = other.fSArgs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFSArgsIsMutable();
            fSArgs_.addAll(other.fSArgs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PbGskReq.pb_req_t_req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PbGskReq.pb_req_t_req) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int fCmd_ ;
      /**
       * <code>optional int32 f_cmd = 1;</code>
       */
      public boolean hasFCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 f_cmd = 1;</code>
       */
      public int getFCmd() {
        return fCmd_;
      }
      /**
       * <code>optional int32 f_cmd = 1;</code>
       */
      public Builder setFCmd(int value) {
        bitField0_ |= 0x00000001;
        fCmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 f_cmd = 1;</code>
       */
      public Builder clearFCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fCmd_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> fIArgs_ = java.util.Collections.emptyList();
      private void ensureFIArgsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          fIArgs_ = new java.util.ArrayList<java.lang.Integer>(fIArgs_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 f_i_args = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getFIArgsList() {
        return java.util.Collections.unmodifiableList(fIArgs_);
      }
      /**
       * <code>repeated int32 f_i_args = 2;</code>
       */
      public int getFIArgsCount() {
        return fIArgs_.size();
      }
      /**
       * <code>repeated int32 f_i_args = 2;</code>
       */
      public int getFIArgs(int index) {
        return fIArgs_.get(index);
      }
      /**
       * <code>repeated int32 f_i_args = 2;</code>
       */
      public Builder setFIArgs(
          int index, int value) {
        ensureFIArgsIsMutable();
        fIArgs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 f_i_args = 2;</code>
       */
      public Builder addFIArgs(int value) {
        ensureFIArgsIsMutable();
        fIArgs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 f_i_args = 2;</code>
       */
      public Builder addAllFIArgs(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFIArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fIArgs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 f_i_args = 2;</code>
       */
      public Builder clearFIArgs() {
        fIArgs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fSArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFSArgsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          fSArgs_ = new com.google.protobuf.LazyStringArrayList(fSArgs_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFSArgsList() {
        return fSArgs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public int getFSArgsCount() {
        return fSArgs_.size();
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public java.lang.String getFSArgs(int index) {
        return fSArgs_.get(index);
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFSArgsBytes(int index) {
        return fSArgs_.getByteString(index);
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public Builder setFSArgs(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFSArgsIsMutable();
        fSArgs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public Builder addFSArgs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFSArgsIsMutable();
        fSArgs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public Builder addAllFSArgs(
          java.lang.Iterable<java.lang.String> values) {
        ensureFSArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fSArgs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public Builder clearFSArgs() {
        fSArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string f_s_args = 3;</code>
       */
      public Builder addFSArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFSArgsIsMutable();
        fSArgs_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb_req_t_req)
    }

    static {
      defaultInstance = new pb_req_t_req(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb_req_t_req)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_req_t_req_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_req_t_req_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pb_gsk_req.proto\"A\n\014pb_req_t_req\022\r\n\005f_" +
      "cmd\030\001 \001(\005\022\020\n\010f_i_args\030\002 \003(\005\022\020\n\010f_s_args\030" +
      "\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_req_t_req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_req_t_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_req_t_req_descriptor,
        new java.lang.String[] { "FCmd", "FIArgs", "FSArgs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
