// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class PbReqAttach;
@class PbReqAttachBuilder;
@class PbReqBaseFile;
@class PbReqBaseFileBuilder;
@class PbReqDepartment;
@class PbReqDepartmentBuilder;
@class PbReqMilestore;
@class PbReqMilestoreBuilder;
@class PbReqMsgBook;
@class PbReqMsgBookBuilder;
@class PbReqMsgHotspot;
@class PbReqMsgHotspotBuilder;
@class PbReqProject;
@class PbReqProjectBuilder;
@class PbReqReport;
@class PbReqReportBuilder;
@class PbReqReq;
@class PbReqReqBuilder;
@class PbReqTask;
@class PbReqTaskBuilder;
@class PbReqTaskReport;
@class PbReqTaskReportBuilder;
@class PbReqUser;
@class PbReqUserBuilder;
@class PbReqUserDataReq;
@class PbReqUserDataReqBuilder;



@interface PbGskReqRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define PbReqAttach_AttachName @"attachName"
#define PbReqAttach_AttachType @"attachType"
#define PbReqAttach_AttachUrl @"attachUrl"
#define PbReqAttach_AttachSize @"attachSize"
#define PbReqAttach_AttachPlaytime @"attachPlaytime"
#define PbReqAttach_AttachUploadtime @"attachUploadtime"
#define PbReqAttach_AttachId @"attachId"
@interface PbReqAttach : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAttachType_:1;
  BOOL hasAttachSize_:1;
  BOOL hasAttachPlaytime_:1;
  BOOL hasAttachUploadtime_:1;
  BOOL hasAttachName_:1;
  BOOL hasAttachUrl_:1;
  BOOL hasAttachId_:1;
  SInt32 attachType;
  SInt32 attachSize;
  SInt32 attachPlaytime;
  SInt32 attachUploadtime;
  NSString* attachName;
  NSString* attachUrl;
  NSString* attachId;
}
- (BOOL) hasAttachName;
- (BOOL) hasAttachType;
- (BOOL) hasAttachUrl;
- (BOOL) hasAttachSize;
- (BOOL) hasAttachPlaytime;
- (BOOL) hasAttachUploadtime;
- (BOOL) hasAttachId;
@property (readonly, strong) NSString* attachName;
@property (readonly) SInt32 attachType;
@property (readonly, strong) NSString* attachUrl;
@property (readonly) SInt32 attachSize;
@property (readonly) SInt32 attachPlaytime;
@property (readonly) SInt32 attachUploadtime;
@property (readonly, strong) NSString* attachId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqAttachBuilder*) builder;
+ (PbReqAttachBuilder*) builder;
+ (PbReqAttachBuilder*) builderWithPrototype:(PbReqAttach*) prototype;
- (PbReqAttachBuilder*) toBuilder;

+ (PbReqAttach*) parseFromData:(NSData*) data;
+ (PbReqAttach*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqAttach*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqAttach*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqAttach*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqAttach*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqAttachBuilder : PBGeneratedMessageBuilder {
@private
  PbReqAttach* resultPbReqAttach;
}

- (PbReqAttach*) defaultInstance;

- (PbReqAttachBuilder*) clear;
- (PbReqAttachBuilder*) clone;

- (PbReqAttach*) build;
- (PbReqAttach*) buildPartial;

- (PbReqAttachBuilder*) mergeFrom:(PbReqAttach*) other;
- (PbReqAttachBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqAttachBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAttachName;
- (NSString*) attachName;
- (PbReqAttachBuilder*) setAttachName:(NSString*) value;
- (PbReqAttachBuilder*) clearAttachName;

- (BOOL) hasAttachType;
- (SInt32) attachType;
- (PbReqAttachBuilder*) setAttachType:(SInt32) value;
- (PbReqAttachBuilder*) clearAttachType;

- (BOOL) hasAttachUrl;
- (NSString*) attachUrl;
- (PbReqAttachBuilder*) setAttachUrl:(NSString*) value;
- (PbReqAttachBuilder*) clearAttachUrl;

- (BOOL) hasAttachSize;
- (SInt32) attachSize;
- (PbReqAttachBuilder*) setAttachSize:(SInt32) value;
- (PbReqAttachBuilder*) clearAttachSize;

- (BOOL) hasAttachPlaytime;
- (SInt32) attachPlaytime;
- (PbReqAttachBuilder*) setAttachPlaytime:(SInt32) value;
- (PbReqAttachBuilder*) clearAttachPlaytime;

- (BOOL) hasAttachUploadtime;
- (SInt32) attachUploadtime;
- (PbReqAttachBuilder*) setAttachUploadtime:(SInt32) value;
- (PbReqAttachBuilder*) clearAttachUploadtime;

- (BOOL) hasAttachId;
- (NSString*) attachId;
- (PbReqAttachBuilder*) setAttachId:(NSString*) value;
- (PbReqAttachBuilder*) clearAttachId;
@end

#define PbReqBaseFile_Baseinfo @"baseinfo"
#define PbReqBaseFile_CreUin @"creUin"
#define PbReqBaseFile_CreName @"creName"
#define PbReqBaseFile_JobType @"jobType"
#define PbReqBaseFile_Tag @"tag"
#define PbReqBaseFile_Fid @"fid"
#define PbReqBaseFile_Fpid @"fpid"
@interface PbReqBaseFile : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCreUin_:1;
  BOOL hasCreName_:1;
  BOOL hasJobType_:1;
  BOOL hasTag_:1;
  BOOL hasFid_:1;
  BOOL hasFpid_:1;
  BOOL hasBaseinfo_:1;
  SInt32 creUin;
  NSString* creName;
  NSString* jobType;
  NSString* tag;
  NSString* fid;
  NSString* fpid;
  PbReqAttach* baseinfo;
}
- (BOOL) hasBaseinfo;
- (BOOL) hasCreUin;
- (BOOL) hasCreName;
- (BOOL) hasJobType;
- (BOOL) hasTag;
- (BOOL) hasFid;
- (BOOL) hasFpid;
@property (readonly, strong) PbReqAttach* baseinfo;
@property (readonly) SInt32 creUin;
@property (readonly, strong) NSString* creName;
@property (readonly, strong) NSString* jobType;
@property (readonly, strong) NSString* tag;
@property (readonly, strong) NSString* fid;
@property (readonly, strong) NSString* fpid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqBaseFileBuilder*) builder;
+ (PbReqBaseFileBuilder*) builder;
+ (PbReqBaseFileBuilder*) builderWithPrototype:(PbReqBaseFile*) prototype;
- (PbReqBaseFileBuilder*) toBuilder;

+ (PbReqBaseFile*) parseFromData:(NSData*) data;
+ (PbReqBaseFile*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqBaseFile*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqBaseFile*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqBaseFile*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqBaseFile*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqBaseFileBuilder : PBGeneratedMessageBuilder {
@private
  PbReqBaseFile* resultPbReqBaseFile;
}

- (PbReqBaseFile*) defaultInstance;

- (PbReqBaseFileBuilder*) clear;
- (PbReqBaseFileBuilder*) clone;

- (PbReqBaseFile*) build;
- (PbReqBaseFile*) buildPartial;

- (PbReqBaseFileBuilder*) mergeFrom:(PbReqBaseFile*) other;
- (PbReqBaseFileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqBaseFileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBaseinfo;
- (PbReqAttach*) baseinfo;
- (PbReqBaseFileBuilder*) setBaseinfo:(PbReqAttach*) value;
- (PbReqBaseFileBuilder*) setBaseinfoBuilder:(PbReqAttachBuilder*) builderForValue;
- (PbReqBaseFileBuilder*) mergeBaseinfo:(PbReqAttach*) value;
- (PbReqBaseFileBuilder*) clearBaseinfo;

- (BOOL) hasCreUin;
- (SInt32) creUin;
- (PbReqBaseFileBuilder*) setCreUin:(SInt32) value;
- (PbReqBaseFileBuilder*) clearCreUin;

- (BOOL) hasCreName;
- (NSString*) creName;
- (PbReqBaseFileBuilder*) setCreName:(NSString*) value;
- (PbReqBaseFileBuilder*) clearCreName;

- (BOOL) hasJobType;
- (NSString*) jobType;
- (PbReqBaseFileBuilder*) setJobType:(NSString*) value;
- (PbReqBaseFileBuilder*) clearJobType;

- (BOOL) hasTag;
- (NSString*) tag;
- (PbReqBaseFileBuilder*) setTag:(NSString*) value;
- (PbReqBaseFileBuilder*) clearTag;

- (BOOL) hasFid;
- (NSString*) fid;
- (PbReqBaseFileBuilder*) setFid:(NSString*) value;
- (PbReqBaseFileBuilder*) clearFid;

- (BOOL) hasFpid;
- (NSString*) fpid;
- (PbReqBaseFileBuilder*) setFpid:(NSString*) value;
- (PbReqBaseFileBuilder*) clearFpid;
@end

#define PbReqMsgBook_BookType @"bookType"
#define PbReqMsgBook_BookId @"bookId"
#define PbReqMsgBook_BookName @"bookName"
#define PbReqMsgBook_BookCataId @"bookCataId"
#define PbReqMsgBook_BookCataInfo @"bookCataInfo"
#define PbReqMsgBook_BookSubcataId @"bookSubcataId"
#define PbReqMsgBook_BookSubcataInfo @"bookSubcataInfo"
#define PbReqMsgBook_BookInfoId @"bookInfoId"
#define PbReqMsgBook_BookInfo @"bookInfo"
@interface PbReqMsgBook : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBookType_:1;
  BOOL hasBookId_:1;
  BOOL hasBookName_:1;
  BOOL hasBookCataId_:1;
  BOOL hasBookCataInfo_:1;
  BOOL hasBookSubcataId_:1;
  BOOL hasBookSubcataInfo_:1;
  BOOL hasBookInfoId_:1;
  BOOL hasBookInfo_:1;
  SInt32 bookType;
  NSString* bookId;
  NSString* bookName;
  NSString* bookCataId;
  NSString* bookCataInfo;
  NSString* bookSubcataId;
  NSString* bookSubcataInfo;
  NSString* bookInfoId;
  NSString* bookInfo;
}
- (BOOL) hasBookType;
- (BOOL) hasBookId;
- (BOOL) hasBookName;
- (BOOL) hasBookCataId;
- (BOOL) hasBookCataInfo;
- (BOOL) hasBookSubcataId;
- (BOOL) hasBookSubcataInfo;
- (BOOL) hasBookInfoId;
- (BOOL) hasBookInfo;
@property (readonly) SInt32 bookType;
@property (readonly, strong) NSString* bookId;
@property (readonly, strong) NSString* bookName;
@property (readonly, strong) NSString* bookCataId;
@property (readonly, strong) NSString* bookCataInfo;
@property (readonly, strong) NSString* bookSubcataId;
@property (readonly, strong) NSString* bookSubcataInfo;
@property (readonly, strong) NSString* bookInfoId;
@property (readonly, strong) NSString* bookInfo;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqMsgBookBuilder*) builder;
+ (PbReqMsgBookBuilder*) builder;
+ (PbReqMsgBookBuilder*) builderWithPrototype:(PbReqMsgBook*) prototype;
- (PbReqMsgBookBuilder*) toBuilder;

+ (PbReqMsgBook*) parseFromData:(NSData*) data;
+ (PbReqMsgBook*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqMsgBook*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqMsgBook*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqMsgBook*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqMsgBook*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqMsgBookBuilder : PBGeneratedMessageBuilder {
@private
  PbReqMsgBook* resultPbReqMsgBook;
}

- (PbReqMsgBook*) defaultInstance;

- (PbReqMsgBookBuilder*) clear;
- (PbReqMsgBookBuilder*) clone;

- (PbReqMsgBook*) build;
- (PbReqMsgBook*) buildPartial;

- (PbReqMsgBookBuilder*) mergeFrom:(PbReqMsgBook*) other;
- (PbReqMsgBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqMsgBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBookType;
- (SInt32) bookType;
- (PbReqMsgBookBuilder*) setBookType:(SInt32) value;
- (PbReqMsgBookBuilder*) clearBookType;

- (BOOL) hasBookId;
- (NSString*) bookId;
- (PbReqMsgBookBuilder*) setBookId:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookId;

- (BOOL) hasBookName;
- (NSString*) bookName;
- (PbReqMsgBookBuilder*) setBookName:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookName;

- (BOOL) hasBookCataId;
- (NSString*) bookCataId;
- (PbReqMsgBookBuilder*) setBookCataId:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookCataId;

- (BOOL) hasBookCataInfo;
- (NSString*) bookCataInfo;
- (PbReqMsgBookBuilder*) setBookCataInfo:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookCataInfo;

- (BOOL) hasBookSubcataId;
- (NSString*) bookSubcataId;
- (PbReqMsgBookBuilder*) setBookSubcataId:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookSubcataId;

- (BOOL) hasBookSubcataInfo;
- (NSString*) bookSubcataInfo;
- (PbReqMsgBookBuilder*) setBookSubcataInfo:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookSubcataInfo;

- (BOOL) hasBookInfoId;
- (NSString*) bookInfoId;
- (PbReqMsgBookBuilder*) setBookInfoId:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookInfoId;

- (BOOL) hasBookInfo;
- (NSString*) bookInfo;
- (PbReqMsgBookBuilder*) setBookInfo:(NSString*) value;
- (PbReqMsgBookBuilder*) clearBookInfo;
@end

#define PbReqMsgHotspot_HotspotId @"hotspotId"
#define PbReqMsgHotspot_HotspotTitle @"hotspotTitle"
#define PbReqMsgHotspot_HotspotFirstImage @"hotspotFirstImage"
#define PbReqMsgHotspot_HotspotSourceSite @"hotspotSourceSite"
@interface PbReqMsgHotspot : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHotspotId_:1;
  BOOL hasHotspotTitle_:1;
  BOOL hasHotspotFirstImage_:1;
  BOOL hasHotspotSourceSite_:1;
  NSString* hotspotId;
  NSString* hotspotTitle;
  NSString* hotspotFirstImage;
  NSString* hotspotSourceSite;
}
- (BOOL) hasHotspotId;
- (BOOL) hasHotspotTitle;
- (BOOL) hasHotspotFirstImage;
- (BOOL) hasHotspotSourceSite;
@property (readonly, strong) NSString* hotspotId;
@property (readonly, strong) NSString* hotspotTitle;
@property (readonly, strong) NSString* hotspotFirstImage;
@property (readonly, strong) NSString* hotspotSourceSite;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqMsgHotspotBuilder*) builder;
+ (PbReqMsgHotspotBuilder*) builder;
+ (PbReqMsgHotspotBuilder*) builderWithPrototype:(PbReqMsgHotspot*) prototype;
- (PbReqMsgHotspotBuilder*) toBuilder;

+ (PbReqMsgHotspot*) parseFromData:(NSData*) data;
+ (PbReqMsgHotspot*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqMsgHotspot*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqMsgHotspot*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqMsgHotspot*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqMsgHotspot*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqMsgHotspotBuilder : PBGeneratedMessageBuilder {
@private
  PbReqMsgHotspot* resultPbReqMsgHotspot;
}

- (PbReqMsgHotspot*) defaultInstance;

- (PbReqMsgHotspotBuilder*) clear;
- (PbReqMsgHotspotBuilder*) clone;

- (PbReqMsgHotspot*) build;
- (PbReqMsgHotspot*) buildPartial;

- (PbReqMsgHotspotBuilder*) mergeFrom:(PbReqMsgHotspot*) other;
- (PbReqMsgHotspotBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqMsgHotspotBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHotspotId;
- (NSString*) hotspotId;
- (PbReqMsgHotspotBuilder*) setHotspotId:(NSString*) value;
- (PbReqMsgHotspotBuilder*) clearHotspotId;

- (BOOL) hasHotspotTitle;
- (NSString*) hotspotTitle;
- (PbReqMsgHotspotBuilder*) setHotspotTitle:(NSString*) value;
- (PbReqMsgHotspotBuilder*) clearHotspotTitle;

- (BOOL) hasHotspotFirstImage;
- (NSString*) hotspotFirstImage;
- (PbReqMsgHotspotBuilder*) setHotspotFirstImage:(NSString*) value;
- (PbReqMsgHotspotBuilder*) clearHotspotFirstImage;

- (BOOL) hasHotspotSourceSite;
- (NSString*) hotspotSourceSite;
- (PbReqMsgHotspotBuilder*) setHotspotSourceSite:(NSString*) value;
- (PbReqMsgHotspotBuilder*) clearHotspotSourceSite;
@end

#define PbReqUser_Uin @"uin"
#define PbReqUser_Name @"name"
#define PbReqUser_Phone @"phone"
#define PbReqUser_JobType @"jobType"
#define PbReqUser_JoinContent @"joinContent"
#define PbReqUser_DepId @"depId"
@interface PbReqUser : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasPhone_:1;
  BOOL hasJobType_:1;
  BOOL hasJoinContent_:1;
  BOOL hasDepId_:1;
  BOOL hasUin_:1;
  NSString* name;
  NSString* phone;
  NSString* jobType;
  NSString* joinContent;
  NSString* depId;
  UInt32 uin;
}
- (BOOL) hasUin;
- (BOOL) hasName;
- (BOOL) hasPhone;
- (BOOL) hasJobType;
- (BOOL) hasJoinContent;
- (BOOL) hasDepId;
@property (readonly) UInt32 uin;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* phone;
@property (readonly, strong) NSString* jobType;
@property (readonly, strong) NSString* joinContent;
@property (readonly, strong) NSString* depId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqUserBuilder*) builder;
+ (PbReqUserBuilder*) builder;
+ (PbReqUserBuilder*) builderWithPrototype:(PbReqUser*) prototype;
- (PbReqUserBuilder*) toBuilder;

+ (PbReqUser*) parseFromData:(NSData*) data;
+ (PbReqUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqUser*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqUserBuilder : PBGeneratedMessageBuilder {
@private
  PbReqUser* resultPbReqUser;
}

- (PbReqUser*) defaultInstance;

- (PbReqUserBuilder*) clear;
- (PbReqUserBuilder*) clone;

- (PbReqUser*) build;
- (PbReqUser*) buildPartial;

- (PbReqUserBuilder*) mergeFrom:(PbReqUser*) other;
- (PbReqUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUin;
- (UInt32) uin;
- (PbReqUserBuilder*) setUin:(UInt32) value;
- (PbReqUserBuilder*) clearUin;

- (BOOL) hasName;
- (NSString*) name;
- (PbReqUserBuilder*) setName:(NSString*) value;
- (PbReqUserBuilder*) clearName;

- (BOOL) hasPhone;
- (NSString*) phone;
- (PbReqUserBuilder*) setPhone:(NSString*) value;
- (PbReqUserBuilder*) clearPhone;

- (BOOL) hasJobType;
- (NSString*) jobType;
- (PbReqUserBuilder*) setJobType:(NSString*) value;
- (PbReqUserBuilder*) clearJobType;

- (BOOL) hasJoinContent;
- (NSString*) joinContent;
- (PbReqUserBuilder*) setJoinContent:(NSString*) value;
- (PbReqUserBuilder*) clearJoinContent;

- (BOOL) hasDepId;
- (NSString*) depId;
- (PbReqUserBuilder*) setDepId:(NSString*) value;
- (PbReqUserBuilder*) clearDepId;
@end

#define PbReqProject_PrjName @"prjName"
#define PbReqProject_PrjType @"prjType"
#define PbReqProject_PrjImage @"prjImage"
#define PbReqProject_Province @"province"
#define PbReqProject_City @"city"
#define PbReqProject_PrjAddress @"prjAddress"
#define PbReqProject_FloorArea @"floorArea"
#define PbReqProject_PrjBegin @"prjBegin"
#define PbReqProject_PrjEnd @"prjEnd"
#define PbReqProject_JianzhuDanwei @"jianzhuDanwei"
#define PbReqProject_ShigongDanwei @"shigongDanwei"
#define PbReqProject_JianliDanwei @"jianliDanwei"
#define PbReqProject_FenbaoDanwei @"fenbaoDanwei"
#define PbReqProject_Lat @"lat"
#define PbReqProject_Lon @"lon"
#define PbReqProject_FloatFloorArea @"floatFloorArea"
@interface PbReqProject : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLat_:1;
  BOOL hasLon_:1;
  BOOL hasFloatFloorArea_:1;
  BOOL hasPrjType_:1;
  BOOL hasFloorArea_:1;
  BOOL hasPrjBegin_:1;
  BOOL hasPrjEnd_:1;
  BOOL hasPrjName_:1;
  BOOL hasPrjImage_:1;
  BOOL hasProvince_:1;
  BOOL hasCity_:1;
  BOOL hasPrjAddress_:1;
  BOOL hasJianzhuDanwei_:1;
  BOOL hasShigongDanwei_:1;
  BOOL hasJianliDanwei_:1;
  BOOL hasFenbaoDanwei_:1;
  Float64 lat;
  Float64 lon;
  Float32 floatFloorArea;
  SInt32 prjType;
  SInt32 floorArea;
  SInt32 prjBegin;
  SInt32 prjEnd;
  NSString* prjName;
  NSString* prjImage;
  NSString* province;
  NSString* city;
  NSString* prjAddress;
  NSString* jianzhuDanwei;
  NSString* shigongDanwei;
  NSString* jianliDanwei;
  NSString* fenbaoDanwei;
}
- (BOOL) hasPrjName;
- (BOOL) hasPrjType;
- (BOOL) hasPrjImage;
- (BOOL) hasProvince;
- (BOOL) hasCity;
- (BOOL) hasPrjAddress;
- (BOOL) hasFloorArea;
- (BOOL) hasPrjBegin;
- (BOOL) hasPrjEnd;
- (BOOL) hasJianzhuDanwei;
- (BOOL) hasShigongDanwei;
- (BOOL) hasJianliDanwei;
- (BOOL) hasFenbaoDanwei;
- (BOOL) hasLat;
- (BOOL) hasLon;
- (BOOL) hasFloatFloorArea;
@property (readonly, strong) NSString* prjName;
@property (readonly) SInt32 prjType;
@property (readonly, strong) NSString* prjImage;
@property (readonly, strong) NSString* province;
@property (readonly, strong) NSString* city;
@property (readonly, strong) NSString* prjAddress;
@property (readonly) SInt32 floorArea;
@property (readonly) SInt32 prjBegin;
@property (readonly) SInt32 prjEnd;
@property (readonly, strong) NSString* jianzhuDanwei;
@property (readonly, strong) NSString* shigongDanwei;
@property (readonly, strong) NSString* jianliDanwei;
@property (readonly, strong) NSString* fenbaoDanwei;
@property (readonly) Float64 lat;
@property (readonly) Float64 lon;
@property (readonly) Float32 floatFloorArea;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqProjectBuilder*) builder;
+ (PbReqProjectBuilder*) builder;
+ (PbReqProjectBuilder*) builderWithPrototype:(PbReqProject*) prototype;
- (PbReqProjectBuilder*) toBuilder;

+ (PbReqProject*) parseFromData:(NSData*) data;
+ (PbReqProject*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqProject*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqProject*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqProject*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqProject*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqProjectBuilder : PBGeneratedMessageBuilder {
@private
  PbReqProject* resultPbReqProject;
}

- (PbReqProject*) defaultInstance;

- (PbReqProjectBuilder*) clear;
- (PbReqProjectBuilder*) clone;

- (PbReqProject*) build;
- (PbReqProject*) buildPartial;

- (PbReqProjectBuilder*) mergeFrom:(PbReqProject*) other;
- (PbReqProjectBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqProjectBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPrjName;
- (NSString*) prjName;
- (PbReqProjectBuilder*) setPrjName:(NSString*) value;
- (PbReqProjectBuilder*) clearPrjName;

- (BOOL) hasPrjType;
- (SInt32) prjType;
- (PbReqProjectBuilder*) setPrjType:(SInt32) value;
- (PbReqProjectBuilder*) clearPrjType;

- (BOOL) hasPrjImage;
- (NSString*) prjImage;
- (PbReqProjectBuilder*) setPrjImage:(NSString*) value;
- (PbReqProjectBuilder*) clearPrjImage;

- (BOOL) hasProvince;
- (NSString*) province;
- (PbReqProjectBuilder*) setProvince:(NSString*) value;
- (PbReqProjectBuilder*) clearProvince;

- (BOOL) hasCity;
- (NSString*) city;
- (PbReqProjectBuilder*) setCity:(NSString*) value;
- (PbReqProjectBuilder*) clearCity;

- (BOOL) hasPrjAddress;
- (NSString*) prjAddress;
- (PbReqProjectBuilder*) setPrjAddress:(NSString*) value;
- (PbReqProjectBuilder*) clearPrjAddress;

- (BOOL) hasFloorArea;
- (SInt32) floorArea;
- (PbReqProjectBuilder*) setFloorArea:(SInt32) value;
- (PbReqProjectBuilder*) clearFloorArea;

- (BOOL) hasPrjBegin;
- (SInt32) prjBegin;
- (PbReqProjectBuilder*) setPrjBegin:(SInt32) value;
- (PbReqProjectBuilder*) clearPrjBegin;

- (BOOL) hasPrjEnd;
- (SInt32) prjEnd;
- (PbReqProjectBuilder*) setPrjEnd:(SInt32) value;
- (PbReqProjectBuilder*) clearPrjEnd;

- (BOOL) hasJianzhuDanwei;
- (NSString*) jianzhuDanwei;
- (PbReqProjectBuilder*) setJianzhuDanwei:(NSString*) value;
- (PbReqProjectBuilder*) clearJianzhuDanwei;

- (BOOL) hasShigongDanwei;
- (NSString*) shigongDanwei;
- (PbReqProjectBuilder*) setShigongDanwei:(NSString*) value;
- (PbReqProjectBuilder*) clearShigongDanwei;

- (BOOL) hasJianliDanwei;
- (NSString*) jianliDanwei;
- (PbReqProjectBuilder*) setJianliDanwei:(NSString*) value;
- (PbReqProjectBuilder*) clearJianliDanwei;

- (BOOL) hasFenbaoDanwei;
- (NSString*) fenbaoDanwei;
- (PbReqProjectBuilder*) setFenbaoDanwei:(NSString*) value;
- (PbReqProjectBuilder*) clearFenbaoDanwei;

- (BOOL) hasLat;
- (Float64) lat;
- (PbReqProjectBuilder*) setLat:(Float64) value;
- (PbReqProjectBuilder*) clearLat;

- (BOOL) hasLon;
- (Float64) lon;
- (PbReqProjectBuilder*) setLon:(Float64) value;
- (PbReqProjectBuilder*) clearLon;

- (BOOL) hasFloatFloorArea;
- (Float32) floatFloorArea;
- (PbReqProjectBuilder*) setFloatFloorArea:(Float32) value;
- (PbReqProjectBuilder*) clearFloatFloorArea;
@end

#define PbReqTaskReport_ReportId @"reportId"
#define PbReqTaskReport_Sponsor @"sponsor"
#define PbReqTaskReport_ReplyTo @"replyTo"
#define PbReqTaskReport_Title @"title"
#define PbReqTaskReport_Content @"content"
#define PbReqTaskReport_ContentType @"contentType"
#define PbReqTaskReport_Playtime @"playtime"
#define PbReqTaskReport_AttachList @"attachList"
#define PbReqTaskReport_ReportTime @"reportTime"
@interface PbReqTaskReport : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasContentType_:1;
  BOOL hasPlaytime_:1;
  BOOL hasReportTime_:1;
  BOOL hasReportId_:1;
  BOOL hasTitle_:1;
  BOOL hasContent_:1;
  BOOL hasSponsor_:1;
  BOOL hasReplyTo_:1;
  SInt32 contentType;
  SInt32 playtime;
  SInt32 reportTime;
  NSString* reportId;
  NSString* title;
  NSString* content;
  PbReqUser* sponsor;
  PbReqUser* replyTo;
  NSMutableArray * attachListArray;
}
- (BOOL) hasReportId;
- (BOOL) hasSponsor;
- (BOOL) hasReplyTo;
- (BOOL) hasTitle;
- (BOOL) hasContent;
- (BOOL) hasContentType;
- (BOOL) hasPlaytime;
- (BOOL) hasReportTime;
@property (readonly, strong) NSString* reportId;
@property (readonly, strong) PbReqUser* sponsor;
@property (readonly, strong) PbReqUser* replyTo;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* content;
@property (readonly) SInt32 contentType;
@property (readonly) SInt32 playtime;
@property (readonly, strong) NSArray * attachList;
@property (readonly) SInt32 reportTime;
- (PbReqBaseFile*)attachListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqTaskReportBuilder*) builder;
+ (PbReqTaskReportBuilder*) builder;
+ (PbReqTaskReportBuilder*) builderWithPrototype:(PbReqTaskReport*) prototype;
- (PbReqTaskReportBuilder*) toBuilder;

+ (PbReqTaskReport*) parseFromData:(NSData*) data;
+ (PbReqTaskReport*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqTaskReport*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqTaskReport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqTaskReport*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqTaskReport*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqTaskReportBuilder : PBGeneratedMessageBuilder {
@private
  PbReqTaskReport* resultPbReqTaskReport;
}

- (PbReqTaskReport*) defaultInstance;

- (PbReqTaskReportBuilder*) clear;
- (PbReqTaskReportBuilder*) clone;

- (PbReqTaskReport*) build;
- (PbReqTaskReport*) buildPartial;

- (PbReqTaskReportBuilder*) mergeFrom:(PbReqTaskReport*) other;
- (PbReqTaskReportBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqTaskReportBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasReportId;
- (NSString*) reportId;
- (PbReqTaskReportBuilder*) setReportId:(NSString*) value;
- (PbReqTaskReportBuilder*) clearReportId;

- (BOOL) hasSponsor;
- (PbReqUser*) sponsor;
- (PbReqTaskReportBuilder*) setSponsor:(PbReqUser*) value;
- (PbReqTaskReportBuilder*) setSponsorBuilder:(PbReqUserBuilder*) builderForValue;
- (PbReqTaskReportBuilder*) mergeSponsor:(PbReqUser*) value;
- (PbReqTaskReportBuilder*) clearSponsor;

- (BOOL) hasReplyTo;
- (PbReqUser*) replyTo;
- (PbReqTaskReportBuilder*) setReplyTo:(PbReqUser*) value;
- (PbReqTaskReportBuilder*) setReplyToBuilder:(PbReqUserBuilder*) builderForValue;
- (PbReqTaskReportBuilder*) mergeReplyTo:(PbReqUser*) value;
- (PbReqTaskReportBuilder*) clearReplyTo;

- (BOOL) hasTitle;
- (NSString*) title;
- (PbReqTaskReportBuilder*) setTitle:(NSString*) value;
- (PbReqTaskReportBuilder*) clearTitle;

- (BOOL) hasContent;
- (NSString*) content;
- (PbReqTaskReportBuilder*) setContent:(NSString*) value;
- (PbReqTaskReportBuilder*) clearContent;

- (BOOL) hasContentType;
- (SInt32) contentType;
- (PbReqTaskReportBuilder*) setContentType:(SInt32) value;
- (PbReqTaskReportBuilder*) clearContentType;

- (BOOL) hasPlaytime;
- (SInt32) playtime;
- (PbReqTaskReportBuilder*) setPlaytime:(SInt32) value;
- (PbReqTaskReportBuilder*) clearPlaytime;

- (NSMutableArray *)attachList;
- (PbReqBaseFile*)attachListAtIndex:(NSUInteger)index;
- (PbReqTaskReportBuilder *)addAttachList:(PbReqBaseFile*)value;
- (PbReqTaskReportBuilder *)setAttachListArray:(NSArray *)array;
- (PbReqTaskReportBuilder *)clearAttachList;

- (BOOL) hasReportTime;
- (SInt32) reportTime;
- (PbReqTaskReportBuilder*) setReportTime:(SInt32) value;
- (PbReqTaskReportBuilder*) clearReportTime;
@end

#define PbReqTask_TaskId @"taskId"
#define PbReqTask_TaskType @"taskType"
#define PbReqTask_PrjId @"prjId"
#define PbReqTask_TaskDesc @"taskDesc"
#define PbReqTask_TaskDescType @"taskDescType"
#define PbReqTask_Playtime @"playtime"
#define PbReqTask_Sponsor @"sponsor"
#define PbReqTask_Members @"members"
#define PbReqTask_Position @"position"
#define PbReqTask_TaskStatus @"taskStatus"
#define PbReqTask_AttachList @"attachList"
#define PbReqTask_ReportList @"reportList"
#define PbReqTask_TaskBegin @"taskBegin"
#define PbReqTask_TaskEnd @"taskEnd"
@interface PbReqTask : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTaskType_:1;
  BOOL hasTaskDescType_:1;
  BOOL hasPlaytime_:1;
  BOOL hasTaskStatus_:1;
  BOOL hasTaskBegin_:1;
  BOOL hasTaskEnd_:1;
  BOOL hasTaskId_:1;
  BOOL hasPrjId_:1;
  BOOL hasTaskDesc_:1;
  BOOL hasPosition_:1;
  BOOL hasSponsor_:1;
  SInt32 taskType;
  SInt32 taskDescType;
  SInt32 playtime;
  SInt32 taskStatus;
  SInt32 taskBegin;
  SInt32 taskEnd;
  NSString* taskId;
  NSString* prjId;
  NSString* taskDesc;
  NSString* position;
  PbReqUser* sponsor;
  NSMutableArray * membersArray;
  NSMutableArray * attachListArray;
  NSMutableArray * reportListArray;
}
- (BOOL) hasTaskId;
- (BOOL) hasTaskType;
- (BOOL) hasPrjId;
- (BOOL) hasTaskDesc;
- (BOOL) hasTaskDescType;
- (BOOL) hasPlaytime;
- (BOOL) hasSponsor;
- (BOOL) hasPosition;
- (BOOL) hasTaskStatus;
- (BOOL) hasTaskBegin;
- (BOOL) hasTaskEnd;
@property (readonly, strong) NSString* taskId;
@property (readonly) SInt32 taskType;
@property (readonly, strong) NSString* prjId;
@property (readonly, strong) NSString* taskDesc;
@property (readonly) SInt32 taskDescType;
@property (readonly) SInt32 playtime;
@property (readonly, strong) PbReqUser* sponsor;
@property (readonly, strong) NSArray * members;
@property (readonly, strong) NSString* position;
@property (readonly) SInt32 taskStatus;
@property (readonly, strong) NSArray * attachList;
@property (readonly, strong) NSArray * reportList;
@property (readonly) SInt32 taskBegin;
@property (readonly) SInt32 taskEnd;
- (PbReqUser*)membersAtIndex:(NSUInteger)index;
- (PbReqBaseFile*)attachListAtIndex:(NSUInteger)index;
- (PbReqTaskReport*)reportListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqTaskBuilder*) builder;
+ (PbReqTaskBuilder*) builder;
+ (PbReqTaskBuilder*) builderWithPrototype:(PbReqTask*) prototype;
- (PbReqTaskBuilder*) toBuilder;

+ (PbReqTask*) parseFromData:(NSData*) data;
+ (PbReqTask*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqTask*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqTask*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqTask*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqTask*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqTaskBuilder : PBGeneratedMessageBuilder {
@private
  PbReqTask* resultPbReqTask;
}

- (PbReqTask*) defaultInstance;

- (PbReqTaskBuilder*) clear;
- (PbReqTaskBuilder*) clone;

- (PbReqTask*) build;
- (PbReqTask*) buildPartial;

- (PbReqTaskBuilder*) mergeFrom:(PbReqTask*) other;
- (PbReqTaskBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqTaskBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (PbReqTaskBuilder*) setTaskId:(NSString*) value;
- (PbReqTaskBuilder*) clearTaskId;

- (BOOL) hasTaskType;
- (SInt32) taskType;
- (PbReqTaskBuilder*) setTaskType:(SInt32) value;
- (PbReqTaskBuilder*) clearTaskType;

- (BOOL) hasPrjId;
- (NSString*) prjId;
- (PbReqTaskBuilder*) setPrjId:(NSString*) value;
- (PbReqTaskBuilder*) clearPrjId;

- (BOOL) hasTaskDesc;
- (NSString*) taskDesc;
- (PbReqTaskBuilder*) setTaskDesc:(NSString*) value;
- (PbReqTaskBuilder*) clearTaskDesc;

- (BOOL) hasTaskDescType;
- (SInt32) taskDescType;
- (PbReqTaskBuilder*) setTaskDescType:(SInt32) value;
- (PbReqTaskBuilder*) clearTaskDescType;

- (BOOL) hasPlaytime;
- (SInt32) playtime;
- (PbReqTaskBuilder*) setPlaytime:(SInt32) value;
- (PbReqTaskBuilder*) clearPlaytime;

- (BOOL) hasSponsor;
- (PbReqUser*) sponsor;
- (PbReqTaskBuilder*) setSponsor:(PbReqUser*) value;
- (PbReqTaskBuilder*) setSponsorBuilder:(PbReqUserBuilder*) builderForValue;
- (PbReqTaskBuilder*) mergeSponsor:(PbReqUser*) value;
- (PbReqTaskBuilder*) clearSponsor;

- (NSMutableArray *)members;
- (PbReqUser*)membersAtIndex:(NSUInteger)index;
- (PbReqTaskBuilder *)addMembers:(PbReqUser*)value;
- (PbReqTaskBuilder *)setMembersArray:(NSArray *)array;
- (PbReqTaskBuilder *)clearMembers;

- (BOOL) hasPosition;
- (NSString*) position;
- (PbReqTaskBuilder*) setPosition:(NSString*) value;
- (PbReqTaskBuilder*) clearPosition;

- (BOOL) hasTaskStatus;
- (SInt32) taskStatus;
- (PbReqTaskBuilder*) setTaskStatus:(SInt32) value;
- (PbReqTaskBuilder*) clearTaskStatus;

- (NSMutableArray *)attachList;
- (PbReqBaseFile*)attachListAtIndex:(NSUInteger)index;
- (PbReqTaskBuilder *)addAttachList:(PbReqBaseFile*)value;
- (PbReqTaskBuilder *)setAttachListArray:(NSArray *)array;
- (PbReqTaskBuilder *)clearAttachList;

- (NSMutableArray *)reportList;
- (PbReqTaskReport*)reportListAtIndex:(NSUInteger)index;
- (PbReqTaskBuilder *)addReportList:(PbReqTaskReport*)value;
- (PbReqTaskBuilder *)setReportListArray:(NSArray *)array;
- (PbReqTaskBuilder *)clearReportList;

- (BOOL) hasTaskBegin;
- (SInt32) taskBegin;
- (PbReqTaskBuilder*) setTaskBegin:(SInt32) value;
- (PbReqTaskBuilder*) clearTaskBegin;

- (BOOL) hasTaskEnd;
- (SInt32) taskEnd;
- (PbReqTaskBuilder*) setTaskEnd:(SInt32) value;
- (PbReqTaskBuilder*) clearTaskEnd;
@end

#define PbReqReport_PhoneInfo @"phoneInfo"
#define PbReqReport_Os @"os"
#define PbReqReport_Sp @"sp"
#define PbReqReport_Network @"network"
@interface PbReqReport : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPhoneInfo_:1;
  BOOL hasOs_:1;
  BOOL hasSp_:1;
  BOOL hasNetwork_:1;
  NSString* phoneInfo;
  NSString* os;
  NSString* sp;
  NSString* network;
}
- (BOOL) hasPhoneInfo;
- (BOOL) hasOs;
- (BOOL) hasSp;
- (BOOL) hasNetwork;
@property (readonly, strong) NSString* phoneInfo;
@property (readonly, strong) NSString* os;
@property (readonly, strong) NSString* sp;
@property (readonly, strong) NSString* network;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqReportBuilder*) builder;
+ (PbReqReportBuilder*) builder;
+ (PbReqReportBuilder*) builderWithPrototype:(PbReqReport*) prototype;
- (PbReqReportBuilder*) toBuilder;

+ (PbReqReport*) parseFromData:(NSData*) data;
+ (PbReqReport*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqReport*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqReport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqReport*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqReport*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqReportBuilder : PBGeneratedMessageBuilder {
@private
  PbReqReport* resultPbReqReport;
}

- (PbReqReport*) defaultInstance;

- (PbReqReportBuilder*) clear;
- (PbReqReportBuilder*) clone;

- (PbReqReport*) build;
- (PbReqReport*) buildPartial;

- (PbReqReportBuilder*) mergeFrom:(PbReqReport*) other;
- (PbReqReportBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqReportBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneInfo;
- (NSString*) phoneInfo;
- (PbReqReportBuilder*) setPhoneInfo:(NSString*) value;
- (PbReqReportBuilder*) clearPhoneInfo;

- (BOOL) hasOs;
- (NSString*) os;
- (PbReqReportBuilder*) setOs:(NSString*) value;
- (PbReqReportBuilder*) clearOs;

- (BOOL) hasSp;
- (NSString*) sp;
- (PbReqReportBuilder*) setSp:(NSString*) value;
- (PbReqReportBuilder*) clearSp;

- (BOOL) hasNetwork;
- (NSString*) network;
- (PbReqReportBuilder*) setNetwork:(NSString*) value;
- (PbReqReportBuilder*) clearNetwork;
@end

#define PbReqUserDataReq_Flag @"flag"
#define PbReqUserDataReq_SArgs @"sargs"
#define PbReqUserDataReq_PageNO @"pageNo"
#define PbReqUserDataReq_PageSize @"pageSize"
@interface PbReqUserDataReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasFlag_:1;
  BOOL hasPageNo_:1;
  BOOL hasPageSize_:1;
  SInt32 flag;
  SInt32 pageNo;
  NSString* pageSize;
  NSMutableArray * sargsArray;
}
- (BOOL) hasFlag;
- (BOOL) hasPageNo;
- (BOOL) hasPageSize;
@property (readonly) SInt32 flag;
@property (readonly, strong) NSArray * sargs;
@property (readonly) SInt32 pageNo;
@property (readonly, strong) NSString* pageSize;
- (NSString*)sargsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqUserDataReqBuilder*) builder;
+ (PbReqUserDataReqBuilder*) builder;
+ (PbReqUserDataReqBuilder*) builderWithPrototype:(PbReqUserDataReq*) prototype;
- (PbReqUserDataReqBuilder*) toBuilder;

+ (PbReqUserDataReq*) parseFromData:(NSData*) data;
+ (PbReqUserDataReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqUserDataReq*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqUserDataReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqUserDataReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqUserDataReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqUserDataReqBuilder : PBGeneratedMessageBuilder {
@private
  PbReqUserDataReq* resultPbReqUserDataReq;
}

- (PbReqUserDataReq*) defaultInstance;

- (PbReqUserDataReqBuilder*) clear;
- (PbReqUserDataReqBuilder*) clone;

- (PbReqUserDataReq*) build;
- (PbReqUserDataReq*) buildPartial;

- (PbReqUserDataReqBuilder*) mergeFrom:(PbReqUserDataReq*) other;
- (PbReqUserDataReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqUserDataReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFlag;
- (SInt32) flag;
- (PbReqUserDataReqBuilder*) setFlag:(SInt32) value;
- (PbReqUserDataReqBuilder*) clearFlag;

- (NSMutableArray *)sargs;
- (NSString*)sargsAtIndex:(NSUInteger)index;
- (PbReqUserDataReqBuilder *)addSargs:(NSString*)value;
- (PbReqUserDataReqBuilder *)setSargsArray:(NSArray *)array;
- (PbReqUserDataReqBuilder *)clearSargs;

- (BOOL) hasPageNo;
- (SInt32) pageNo;
- (PbReqUserDataReqBuilder*) setPageNo:(SInt32) value;
- (PbReqUserDataReqBuilder*) clearPageNo;

- (BOOL) hasPageSize;
- (NSString*) pageSize;
- (PbReqUserDataReqBuilder*) setPageSize:(NSString*) value;
- (PbReqUserDataReqBuilder*) clearPageSize;
@end

#define PbReqMilestore_Time @"time"
#define PbReqMilestore_Event @"event"
@interface PbReqMilestore : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTime_:1;
  BOOL hasEvent_:1;
  SInt32 time;
  NSString* event;
}
- (BOOL) hasTime;
- (BOOL) hasEvent;
@property (readonly) SInt32 time;
@property (readonly, strong) NSString* event;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqMilestoreBuilder*) builder;
+ (PbReqMilestoreBuilder*) builder;
+ (PbReqMilestoreBuilder*) builderWithPrototype:(PbReqMilestore*) prototype;
- (PbReqMilestoreBuilder*) toBuilder;

+ (PbReqMilestore*) parseFromData:(NSData*) data;
+ (PbReqMilestore*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqMilestore*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqMilestore*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqMilestore*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqMilestore*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqMilestoreBuilder : PBGeneratedMessageBuilder {
@private
  PbReqMilestore* resultPbReqMilestore;
}

- (PbReqMilestore*) defaultInstance;

- (PbReqMilestoreBuilder*) clear;
- (PbReqMilestoreBuilder*) clone;

- (PbReqMilestore*) build;
- (PbReqMilestore*) buildPartial;

- (PbReqMilestoreBuilder*) mergeFrom:(PbReqMilestore*) other;
- (PbReqMilestoreBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqMilestoreBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTime;
- (SInt32) time;
- (PbReqMilestoreBuilder*) setTime:(SInt32) value;
- (PbReqMilestoreBuilder*) clearTime;

- (BOOL) hasEvent;
- (NSString*) event;
- (PbReqMilestoreBuilder*) setEvent:(NSString*) value;
- (PbReqMilestoreBuilder*) clearEvent;
@end

#define PbReqDepartment_Id @"id"
#define PbReqDepartment_Name @"name"
@interface PbReqDepartment : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  NSString* id;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
@property (readonly, strong) NSString* id;
@property (readonly, strong) NSString* name;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqDepartmentBuilder*) builder;
+ (PbReqDepartmentBuilder*) builder;
+ (PbReqDepartmentBuilder*) builderWithPrototype:(PbReqDepartment*) prototype;
- (PbReqDepartmentBuilder*) toBuilder;

+ (PbReqDepartment*) parseFromData:(NSData*) data;
+ (PbReqDepartment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqDepartment*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqDepartment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqDepartment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqDepartment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqDepartmentBuilder : PBGeneratedMessageBuilder {
@private
  PbReqDepartment* resultPbReqDepartment;
}

- (PbReqDepartment*) defaultInstance;

- (PbReqDepartmentBuilder*) clear;
- (PbReqDepartmentBuilder*) clone;

- (PbReqDepartment*) build;
- (PbReqDepartment*) buildPartial;

- (PbReqDepartmentBuilder*) mergeFrom:(PbReqDepartment*) other;
- (PbReqDepartmentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqDepartmentBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (PbReqDepartmentBuilder*) setId:(NSString*) value;
- (PbReqDepartmentBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (PbReqDepartmentBuilder*) setName:(NSString*) value;
- (PbReqDepartmentBuilder*) clearName;
@end

#define PbReqReq_Cmd @"cmd"
#define PbReqReq_IArgs @"iargs"
#define PbReqReq_SArgs @"sargs"
#define PbReqReq_Attch @"attch"
#define PbReqReq_Project @"project"
#define PbReqReq_PrjMember @"prjMember"
#define PbReqReq_Task @"task"
#define PbReqReq_Report @"report"
#define PbReqReq_UserDataReq @"userDataReq"
#define PbReqReq_MsgBook @"msgBook"
#define PbReqReq_MsgHotspot @"msgHotspot"
#define PbReqReq_Milestore @"milestore"
#define PbReqReq_Department @"department"
#define PbReqReq_TurnDepartment @"turnDepartment"
@interface PbReqReq : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCmd_:1;
  BOOL hasProject_:1;
  BOOL hasTask_:1;
  BOOL hasReport_:1;
  BOOL hasUserDataReq_:1;
  BOOL hasMsgBook_:1;
  BOOL hasMsgHotspot_:1;
  BOOL hasTurnDepartment_:1;
  SInt32 cmd;
  PbReqProject* project;
  PbReqTask* task;
  PbReqReport* report;
  PbReqUserDataReq* userDataReq;
  PbReqMsgBook* msgBook;
  PbReqMsgHotspot* msgHotspot;
  PbReqDepartment* turnDepartment;
  PBAppendableArray * iargsArray;
  NSMutableArray * sargsArray;
  NSMutableArray * attchArray;
  NSMutableArray * prjMemberArray;
  NSMutableArray * milestoreArray;
  NSMutableArray * departmentArray;
}
- (BOOL) hasCmd;
- (BOOL) hasProject;
- (BOOL) hasTask;
- (BOOL) hasReport;
- (BOOL) hasUserDataReq;
- (BOOL) hasMsgBook;
- (BOOL) hasMsgHotspot;
- (BOOL) hasTurnDepartment;
@property (readonly) SInt32 cmd;
@property (readonly, strong) PBArray * iargs;
@property (readonly, strong) NSArray * sargs;
@property (readonly, strong) NSArray * attch;
@property (readonly, strong) PbReqProject* project;
@property (readonly, strong) NSArray * prjMember;
@property (readonly, strong) PbReqTask* task;
@property (readonly, strong) PbReqReport* report;
@property (readonly, strong) PbReqUserDataReq* userDataReq;
@property (readonly, strong) PbReqMsgBook* msgBook;
@property (readonly, strong) PbReqMsgHotspot* msgHotspot;
@property (readonly, strong) NSArray * milestore;
@property (readonly, strong) NSArray * department;
@property (readonly, strong) PbReqDepartment* turnDepartment;
- (SInt32)iargsAtIndex:(NSUInteger)index;
- (NSString*)sargsAtIndex:(NSUInteger)index;
- (PbReqAttach*)attchAtIndex:(NSUInteger)index;
- (PbReqUser*)prjMemberAtIndex:(NSUInteger)index;
- (PbReqMilestore*)milestoreAtIndex:(NSUInteger)index;
- (PbReqDepartment*)departmentAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PbReqReqBuilder*) builder;
+ (PbReqReqBuilder*) builder;
+ (PbReqReqBuilder*) builderWithPrototype:(PbReqReq*) prototype;
- (PbReqReqBuilder*) toBuilder;

+ (PbReqReq*) parseFromData:(NSData*) data;
+ (PbReqReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqReq*) parseFromInputStream:(NSInputStream*) input;
+ (PbReqReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PbReqReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PbReqReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PbReqReqBuilder : PBGeneratedMessageBuilder {
@private
  PbReqReq* resultPbReqReq;
}

- (PbReqReq*) defaultInstance;

- (PbReqReqBuilder*) clear;
- (PbReqReqBuilder*) clone;

- (PbReqReq*) build;
- (PbReqReq*) buildPartial;

- (PbReqReqBuilder*) mergeFrom:(PbReqReq*) other;
- (PbReqReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PbReqReqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCmd;
- (SInt32) cmd;
- (PbReqReqBuilder*) setCmd:(SInt32) value;
- (PbReqReqBuilder*) clearCmd;

- (PBAppendableArray *)iargs;
- (SInt32)iargsAtIndex:(NSUInteger)index;
- (PbReqReqBuilder *)addIargs:(SInt32)value;
- (PbReqReqBuilder *)setIargsArray:(NSArray *)array;
- (PbReqReqBuilder *)setIargsValues:(const SInt32 *)values count:(NSUInteger)count;
- (PbReqReqBuilder *)clearIargs;

- (NSMutableArray *)sargs;
- (NSString*)sargsAtIndex:(NSUInteger)index;
- (PbReqReqBuilder *)addSargs:(NSString*)value;
- (PbReqReqBuilder *)setSargsArray:(NSArray *)array;
- (PbReqReqBuilder *)clearSargs;

- (NSMutableArray *)attch;
- (PbReqAttach*)attchAtIndex:(NSUInteger)index;
- (PbReqReqBuilder *)addAttch:(PbReqAttach*)value;
- (PbReqReqBuilder *)setAttchArray:(NSArray *)array;
- (PbReqReqBuilder *)clearAttch;

- (BOOL) hasProject;
- (PbReqProject*) project;
- (PbReqReqBuilder*) setProject:(PbReqProject*) value;
- (PbReqReqBuilder*) setProjectBuilder:(PbReqProjectBuilder*) builderForValue;
- (PbReqReqBuilder*) mergeProject:(PbReqProject*) value;
- (PbReqReqBuilder*) clearProject;

- (NSMutableArray *)prjMember;
- (PbReqUser*)prjMemberAtIndex:(NSUInteger)index;
- (PbReqReqBuilder *)addPrjMember:(PbReqUser*)value;
- (PbReqReqBuilder *)setPrjMemberArray:(NSArray *)array;
- (PbReqReqBuilder *)clearPrjMember;

- (BOOL) hasTask;
- (PbReqTask*) task;
- (PbReqReqBuilder*) setTask:(PbReqTask*) value;
- (PbReqReqBuilder*) setTaskBuilder:(PbReqTaskBuilder*) builderForValue;
- (PbReqReqBuilder*) mergeTask:(PbReqTask*) value;
- (PbReqReqBuilder*) clearTask;

- (BOOL) hasReport;
- (PbReqReport*) report;
- (PbReqReqBuilder*) setReport:(PbReqReport*) value;
- (PbReqReqBuilder*) setReportBuilder:(PbReqReportBuilder*) builderForValue;
- (PbReqReqBuilder*) mergeReport:(PbReqReport*) value;
- (PbReqReqBuilder*) clearReport;

- (BOOL) hasUserDataReq;
- (PbReqUserDataReq*) userDataReq;
- (PbReqReqBuilder*) setUserDataReq:(PbReqUserDataReq*) value;
- (PbReqReqBuilder*) setUserDataReqBuilder:(PbReqUserDataReqBuilder*) builderForValue;
- (PbReqReqBuilder*) mergeUserDataReq:(PbReqUserDataReq*) value;
- (PbReqReqBuilder*) clearUserDataReq;

- (BOOL) hasMsgBook;
- (PbReqMsgBook*) msgBook;
- (PbReqReqBuilder*) setMsgBook:(PbReqMsgBook*) value;
- (PbReqReqBuilder*) setMsgBookBuilder:(PbReqMsgBookBuilder*) builderForValue;
- (PbReqReqBuilder*) mergeMsgBook:(PbReqMsgBook*) value;
- (PbReqReqBuilder*) clearMsgBook;

- (BOOL) hasMsgHotspot;
- (PbReqMsgHotspot*) msgHotspot;
- (PbReqReqBuilder*) setMsgHotspot:(PbReqMsgHotspot*) value;
- (PbReqReqBuilder*) setMsgHotspotBuilder:(PbReqMsgHotspotBuilder*) builderForValue;
- (PbReqReqBuilder*) mergeMsgHotspot:(PbReqMsgHotspot*) value;
- (PbReqReqBuilder*) clearMsgHotspot;

- (NSMutableArray *)milestore;
- (PbReqMilestore*)milestoreAtIndex:(NSUInteger)index;
- (PbReqReqBuilder *)addMilestore:(PbReqMilestore*)value;
- (PbReqReqBuilder *)setMilestoreArray:(NSArray *)array;
- (PbReqReqBuilder *)clearMilestore;

- (NSMutableArray *)department;
- (PbReqDepartment*)departmentAtIndex:(NSUInteger)index;
- (PbReqReqBuilder *)addDepartment:(PbReqDepartment*)value;
- (PbReqReqBuilder *)setDepartmentArray:(NSArray *)array;
- (PbReqReqBuilder *)clearDepartment;

- (BOOL) hasTurnDepartment;
- (PbReqDepartment*) turnDepartment;
- (PbReqReqBuilder*) setTurnDepartment:(PbReqDepartment*) value;
- (PbReqReqBuilder*) setTurnDepartmentBuilder:(PbReqDepartmentBuilder*) builderForValue;
- (PbReqReqBuilder*) mergeTurnDepartment:(PbReqDepartment*) value;
- (PbReqReqBuilder*) clearTurnDepartment;
@end


// @@protoc_insertion_point(global_scope)
