#!/usr/bin/env python
# -*- coding: utf-8; tab-width: 4; -*-
CMD = {
    "CMD_USER_CREATE"                           : 0x0100 , #//创建用户 
    "CMD_USER_INFO"                             : 0x0101 , #//获取用户数据 
    "CMD_USER_UPDATE_INFO"                      : 0x0102 , #//更新用户信息 
    "CMD_USER_UPLOAD_PHONE_ADDRESS"             : 0x0103 , #//上传通讯录 
    "CMD_USER_REMMEND_FRIEND"                   : 0x0104 , #//通讯录推荐 
    "CMD_USER_FRIEND_INFO"                      : 0x0105 , #//获取用户好友信息 
    "CMD_USER_REMMEND_PROJECT"                  : 0x0106 , #//获取推荐项目 
    "CMD_USER_ADD_COLLECTION"                   : 0x0107 , #//获取用户收藏 
    "CMD_USER_COLLECTION"                       : 0x0108 , #//添加收藏 
    "CMD_USER_DEL_COLLECTION"                   : 0x0109 , #//删除收藏 
    "CMD_USER_FRIEND_ADD"                       : 0x0150 , #//添加好友 
    "CMD_USER_FRIEND_DEL"                       : 0x0151 , #//删除好友 
    "CMD_USER_FRIEND_YES_NO"                    : 0x0152 , #//同意或者拒绝好友 
    "CMD_USER_FRIEND_SEARCH"                    : 0x0153 , #//搜索好友 
    "CMD_USER_FRIEND_REMARK_UPDATE"             : 0x0154 , #//修改好友备注 
    "CMD_USER_FRIEND_ADD_CHECK"                 : 0x0155 , #//检测是否能直接加好友 
    "CMD_IM_SEND_MSG"                           : 0x0201 , #//客户端发送IM消息，包括group消息和单聊消息 
    "CMD_IM_OFFLINE_MSG"                        : 0x0202 , #//客户端拉取离线消息或增量消息同步 
    "CMD_IM_GROUP_CREATE"                       : 0x0203 , #//创建群组 
    "CMD_IM_GROUP_EDIT"                         : 0x0204 , #//修改群组信息 
    "CMD_IM_GROUP_GET"                          : 0x0205 , #//获取群组信息 
    "CMD_IM_GROUP_LIST"                         : 0x0206 , #//获取用户群组列表 
    "CMD_IM_GROUP_USER_INVITE"                  : 0x0207 , #//群组添加成员 
    "CMD_IM_GROUP_USER_DEL"                     : 0x0208 , #//群组删除成员 
    "CMD_IM_GROUP_USER_EDIT"                    : 0x0209 , #//修改群成员信息 
    "CMD_IM_GROUP_REPORT_READ_SEQ"              : 0x0210 , #//上报群阅读最大seqid 
    "CMD_PUSH"                                  : 0xEEEE , #//消息push 
    "CMD_PROJECT_INFO_CREATE"                   : 0x0301 , #//创建项目 
    "CMD_PROJECT_MY_LIST"                       : 0x0302 , #//我的项目列表 
    "CMD_PROJECT_JOIN"                          : 0x0303 , #//加入项目 
    "CMD_PROJECT_QUERY"                         : 0x0304 , #//查询项目列表 
    "CMD_PROJECT_DETAIL"                        : 0x0305 , #//项目详情 
    "CMD_PROJECT_IM_GROUP_CREATE"               : 0x0306 , #//创建项目群聊 
    "CMD_PROJECT_MANAGE"                        : 0x0307 , #//项目管理 
    "CMD_PROJECT_MESSAGE"                       : 0x0308 , #//项目消息 
    "CMD_PROJECT_ADD_MEMBER"                    : 0x0309 , #//添加项目成员 
    "CMD_PROJECT_CHECK_MEMBER"                  : 0x0310 , #//审核项目成员 
    "CMD_PROJECT_DEL_MEMBER"                    : 0x0311 , #//删除项目成员 
    "CMD_PROJECT_ALL_MEMBER"                    : 0x0312 , #//获取项目成员 
    "CMD_PROJECT_OVER_VIEW"                     : 0x0313 , #//项目概览 
    "CMD_PROJECT_QUIT"                          : 0x0314 , #//退出项目 
    "CMD_PROJECT_INFO"                          : 0x0315 , #//项目信息 
    "CMD_PROJECT_WEATHER"                       : 0x0316 , #//项目天气 
    "CMD_PROJECT_UPLOAD_FILE"                   : 0x0317 , #//项目上传云文件 
    "CMD_PROJECT_GET_FILE"                      : 0x0318 , #//获取项目云文件 
    "CMD_PROJECT_INFO_EDIT"                     : 0x0319 , #//编辑项目信息 
    "CMD_PROJECT_EDIT_JOB_TYPE"                 : 0x0320 , #//编辑项目职位 
    "CMD_PROJECT_DEL_FILE"                      : 0x0321 , #//删除项目文件 
    "CMD_PROJECT_FILE_INFO"                     : 0x0322 , #//项目文件信息 
    "CMD_PROJECT_MODIFY_JOB_TYPE"               : 0x0323 , #//修改项目岗位 
    "CMD_PROJECT_EDIT_MILESTORE"                : 0x0324 , #//修改项目里程碑信息 
    "CMD_PROJECT_GET_RECORD_GROUP"              : 0x0325 , #//获取项目记录群组 
    "CMD_PROJECT_ADD_DEPARTMENT"                : 0x0326 , #//添加项目岗位部门 
    "CMD_PROJECT_EDIT_DEPARTMENT"               : 0x0327 , #//编辑项目岗位部门 
    "CMD_PROJECT_DEL_DEPARTMENT"                : 0x0328 , #//删除项目岗位部门 
    "CMD_PROJECT_DELETE"                        : 0x0329 , #//删除项目 
    "CMD_PROJECT_CHANGE_DEPARTMENT"             : 0x0330 , #//调整项目成员所属部门 
    "CMD_TASK_CREATE"                           : 0x0351 , #//创建任务 
    "CMD_TASK_EDIT"                             : 0x0352 , #//修改任务 
    "CMD_TASK_LIST"                             : 0x0353 , #//项目任务列表 
    "CMD_TASK_DETAIL"                           : 0x0354 , #//任务详情 
    "CMD_TASK_REPORT_CREATE"                    : 0x0355 , #//添加任务汇报 
    "CMD_TASK_REPORT_LIST"                      : 0x0356 , #//任务汇报列表 
    "CMD_TASK_VIEW_CREATE"                      : 0x0357 , #//添加任务查看记录 
    "CMD_TASK_VIEW_LIST"                        : 0x0358 , #//任务查看记录列表 
    "CMD_TASK_NOTIFY_CHECK"                     : 0x0359 , #//任务到期、查看通知(知道了) 
    "CMD_TASK_DEL"                              : 0x035A , #//删除任务 
    "CMD_TASK_TIMER_CALL"                       : 0x035B , #//定时器回调 
    "CMD_TASK_NOTIFY"                           : 0x035C , #//小助手通知；如：发起者提醒成员查看 
    "CMD_POSITION_LIST"                         : 0x035D , #//常用部位 
    "CMD_POINTS_INVITEOTHERREG"                 : 0x0904 , #//活动：通过邀请别人，别人注册筑友 
    "CMD_POINTS_ACTIVITYREG"                    : 0x0905 , #//受邀请注册筑友 
    "CMD_USER_SIGUUP"                           : 0x0906 , #//新用户注册 
    "CMD_UTIL_RELOAD_VERSION"                   : 0x7001 , #//清空版本缓存 
    "CMD_UTIL_ADD_VERSION"                      : 0x7002 , #//添加版本 
    "CMD_UTIL_SEND_SYSTEM_MSG"                  : 0x7003 , #//发送小助手消息 
    "CMD_UTIL_USER_ACCOUNT"                     : 0x7101 , #//添加用户 

};
